import type { ConceptDefinition, ConceptRegistry } from '../domain/concepts'
import { countOf } from '../domain/counts'
import type { DomainRegistry, LifeDomainId } from '../domain/domains'
import type { EntityIndex, SemanticEntity } from '../domain/entities'
import type { RecordId } from '../domain/ids'
import { unknown, type KnowledgeState, type Unknown } from '../domain/knowledge'
import { mayRaiseUnasked, type PrivacyClass } from '../domain/privacy'
import {
  bearsConcept,
  evidenceSourceOf,
  type CanonicalRecord,
  type EvidenceStrength,
  type ProvenanceSource,
} from '../domain/records'
import { localDayIdAt, localDaysBetween, type Instant, type TimeZoneId } from '../domain/time'
import { approximateHorizonMs, type ConceptId, type FreshnessHorizon } from '../domain/windows'
import type { MemoryView } from '../memory/view'
import { collectEpisodes } from './lifecycle'
import { outcomeWindowFor } from './outcomes'
import { questionFor } from './questions'
import { refreshingMoveFor } from './refreshing'

/**
 * The coverage engine (canonical plan sections 8, 17.1 step 3, and 63).
 *
 * Section 63 states the failure this file exists to prevent, and states it as a
 * rule rather than a feature: *a domain must not silently remain based on
 * months-old assumptions while the UI gives the impression that the app is
 * current.* A domain is allowed to be quiet. It is not allowed to be quiet
 * without anybody noticing.
 *
 * ## What this adds that concept freshness does not
 *
 * `ConceptDefinition.freshness` already answers a yes/no question about one
 * reading: is this still current? That is enough to stop a three-week-old
 * energy figure being read as today's, and it is not enough to notice that
 * nothing has been heard about the house since April. Three things are missing
 * from it, and they are what coverage is:
 *
 * - **How far past.** Stale by an hour is ordinary life. Stale by four of its
 *   own windows is a subject nobody has mentioned. The distinction has to be
 *   concept-specific for the same reason freshness is — three days of silence
 *   about sleep is neglect and three days of silence about a cash buffer is
 *   nothing at all — so the threshold is derived from the concept's own horizon
 *   rather than from a number in this file.
 * - **The area rather than the reading.** A domain is covered by several
 *   concepts and by what the owner has actually done in it. Clearing the
 *   kitchen is evidence about the house; no concept records it.
 * - **Whether anything is being done about it.** Section 8 gives an order of
 *   preference for repairing coverage, and a stale area with a refresh already
 *   under way is in a different state from one with nothing coming.
 *
 * ## Importance comes from the owner, not from a table here
 *
 * Section 8 says "every important domain", and the tempting implementation is a
 * ranking of the eleven domains written by the developer — which would be this
 * file deciding that faith matters less than career for somebody else's life.
 * So importance is read off the owner's own history: a domain matters to him if
 * he has named something in it, set a goal in it, pointed a week at it, or
 * acted in it. A domain he has never mentioned stays quiet, which is section
 * 4.4 — missing data is not failure — and section 4.5, which forbids collecting
 * data merely because a field exists.
 *
 * Nothing here reads a clock, and nothing here decides. Coverage is a reading
 * of the history at a moment, like the rest of `situation.ts`.
 */

/**
 * How well an area is currently understood.
 *
 * `unheard` and `stale` are deliberately separate, and it is G-009's rule
 * applied to an area instead of a value: never having been told is not the same
 * as having been told once and watching it expire, and an app that flattened
 * them would ask the same question in both cases — which is nagging in the
 * first case and correct in the second.
 */
export type CoverageStatus = 'current' | 'quiet' | 'stale' | 'unheard'

/**
 * How a stale area should be brought back, in section 8's order of preference.
 *
 * > 1. use trustworthy evidence already being generated by normal life;
 * > 2. infer cautiously from related evidence when appropriate;
 * > 3. create a useful action that naturally produces evidence;
 * > 4. ask one small question at an appropriate moment;
 * > 5. surface a "needs update" signal in Life if manual review is actually
 * >    needed.
 *
 * The first two are one route here because they are one behaviour: the app
 * works it out and the owner is not asked. `needs-review` is the last resort
 * and the only one that costs the owner a trip to a Life page, which is why
 * section 8 puts it last and why this engine tries four things first.
 */
export const REFRESH_ROUTES = [
  'already-current',
  'normal-life',
  'an-action',
  'a-question',
  'needs-review',
] as const

/**
 * The routes as a value, so nothing has to copy the list out by hand.
 *
 * `everyStandingWord` did copy it, and its copy said `a-move` — a route that
 * has never existed. It happened to produce the right set of words because the
 * missing `an-action` and the invented `a-move` both fall to the same branch,
 * which is precisely why nobody noticed. A route added to this union now
 * reaches the copy check whether or not anyone remembers to add it there.
 */
export type RefreshRoute = (typeof REFRESH_ROUTES)[number]

/** One sub-area: a concept, and how well it is currently held. */
export interface ConceptCoverage {
  readonly concept: ConceptId
  readonly label: string
  readonly domain: LifeDomainId
  readonly privacy: PrivacyClass
  readonly state: KnowledgeState
  /**
   * Why it is not known, when it is not — QA-82-008.
   *
   * `state` alone says a concept is unknown, and every surface that reads it
   * then has to choose a sentence with nothing to choose from. Insights chose
   * "never answered" for all of them, which is false of the four reasons that
   * sit on top of an answer the record actually holds: withdrawn, contradicted,
   * lapsed and unreadable. The reason is already resolved one layer down; it
   * was simply not carried this far.
   */
  readonly unknown: Unknown | undefined
  /** Whether a gap here is a gap in understanding, or just Tuesday. */
  readonly standing: boolean
  /** Where the most recent evidence came from. Absent when there is none. */
  readonly source: ProvenanceSource | undefined
  /**
   * Every distinct origin behind this, not only the newest (QA-08-001 retest).
   *
   * `source` answers "where did the latest reading come from", which is the
   * right question for reliability and the wrong one for disclosure. A
   * conclusion drawn entirely from imported history should say so, and it can
   * only say so if something knows that *all* of the evidence is imported
   * rather than merely the most recent piece.
   *
   * Sources rather than record ids: the only question asked of this is whether
   * they agree, there are at most six of them, and carrying a decade of ids to
   * answer a yes-or-no would be a list nobody reads.
   */
  readonly sources: readonly ProvenanceSource[]
  readonly lastEvidenceAt: Instant | undefined
  readonly daysSince: number | undefined
  /** After how many quiet days this concept counts as neglected. */
  readonly neglectedAfterDays: number | undefined
  /** Past that mark, and the owner has shown this area matters to him. */
  readonly neglected: boolean
  /** Whether the guide is permitted to spend a question on it right now. */
  readonly askable: boolean
  readonly evidence: readonly RecordId[]
}

export interface DomainCoverage {
  readonly domain: LifeDomainId
  readonly label: string
  readonly status: CoverageStatus
  readonly strength: EvidenceStrength
  /** True when the owner's own history shows this area matters to him. */
  readonly matters: boolean
  /** The last thing that spoke to this area's standing understanding. */
  readonly lastEvidenceAt: Instant | undefined
  readonly daysSinceEvidence: number | undefined
  /**
   * Readable records here dated after the moment being read — QA-82-011.
   *
   * Carried so a surface can tell "nothing yet" from "nothing ever" without
   * walking the history again, and so the two sentences cannot drift apart.
   */
  readonly later: number
  /**
   * When anything at all was last heard about this area, momentary readings
   * included.
   *
   * Separate from `daysSinceEvidence` because they answer different questions
   * and the difference shows on screen. Health has no standing concept in the
   * registry — energy and soreness are both readings of a moment — so its
   * meaningful evidence is whatever he has *done*, and on a history where he
   * has done nothing that would be nothing at all. Reporting Health as an area
   * the app has never heard of, on an evening he answered both questions an
   * hour ago, is the app forgetting what it was just told.
   */
  readonly daysSinceHeard: number | undefined
  /** Where the most recent evidence came from, whatever kind it was. */
  readonly source: ProvenanceSource | undefined
  /**
   * Every distinct origin behind this area. See `ConceptCoverage.sources`.
   *
   * Read from the area's whole evidence rather than from its concepts, because
   * the case this exists for has no concept evidence at all: an area whose only
   * record is an imported goal has nothing bearing a concept, and the overview
   * still says "nothing has come in about career & learning for 3 months" — a
   * conclusion drawn entirely from imported history, which was the still-open
   * half of QA-08-001.
   */
  readonly sources: readonly ProvenanceSource[]
  readonly concepts: readonly ConceptCoverage[]
  /** The sub-area most worth refreshing. Absent when nothing is overdue. */
  readonly weakest: ConceptCoverage | undefined
  readonly refresh: RefreshRoute
  /** Owner-facing, and about the app's knowledge rather than about his life. */
  readonly summary: string
}

export interface CoverageState {
  readonly domains: readonly DomainCoverage[]
  get(domain: LifeDomainId): DomainCoverage | undefined
  /** Areas that matter to the owner and have gone quiet past their own mark. */
  readonly neglected: readonly DomainCoverage[]
  /**
   * The one area most worth doing something about, or nothing.
   *
   * The limiter reads this. Private / Sexual Health is never it — section 11
   * makes that domain manual-entry-first and says outright that the owner
   * should not be treated as though he must answer unsolicited private
   * questions during a normal check-in. A "you have not mentioned this for a
   * while" prompt about it is exactly that, so the domain is covered, reported
   * on Life, and never raised by the app of its own accord.
   */
  readonly mostNeglected: DomainCoverage | undefined
}

export interface CoverageMoment {
  readonly now: Instant
  readonly zone: TimeZoneId
  readonly domains: DomainRegistry
  readonly concepts: ConceptRegistry
}

/**
 * The shortest silence that counts as neglect, per concept.
 *
 * Three of its own freshness windows, floored at a week. The multiple is what
 * makes this concept-specific — twenty-one days for home friction, ninety for a
 * cash buffer, forty-two for a learning topic — and the floor is what stops the
 * shortest horizons turning ordinary life into an alarm: energy goes stale in
 * six hours, and an app that called six hours of silence neglect would be
 * asking how the owner feels three times a day.
 *
 * Durable knowledge is never neglected. A custody arrangement does not decay,
 * which is the case section 8 calls out by name.
 */
const NEGLECT_MULTIPLE = 3
const NEGLECT_FLOOR_DAYS = 7

/**
 * How long a whole area may go without anything at all before it is stale.
 *
 * Four weeks, and it is a domain-level backstop rather than the main rule: some
 * areas have no standing concept in the registry yet — nothing tracks a
 * standing understanding of the owner's social life — and section 8 says every
 * important domain, not every domain the registry happens to model well.
 */
const DOMAIN_QUIET_DAYS = 28

export function neglectedAfterDaysFor(horizon: FreshnessHorizon): number | undefined {
  const ms = approximateHorizonMs(horizon)
  if (ms === undefined) return undefined
  return Math.max(NEGLECT_FLOOR_DAYS, (ms / 86_400_000) * NEGLECT_MULTIPLE)
}

// ---------------------------------------------------------------------------
// What counts as evidence about an area
// ---------------------------------------------------------------------------

interface Evidence {
  readonly at: Instant
  readonly record: RecordId
  readonly source: ProvenanceSource
}

/**
 * Everything in the history that speaks to a domain's standing understanding.
 *
 * Section 8 asks for "last **meaningful** evidence", and the qualifier is the
 * whole of this function. Two things count.
 *
 * A record bearing a **standing** concept — what the owner is studying, what
 * the house is like, how he has been sleeping. A reading of how much time he
 * has tonight is not on the list, and leaving it off is what stops a domain
 * looking freshly understood because somebody tapped "an hour" at six o'clock.
 *
 * And **anything he actually did** in the area. Clearing the kitchen is
 * evidence about the house and no concept records it; section 8 lists evidence
 * as "direct, inferred, or outcome-based", which presupposes all three count.
 * The envelope's own `domains` list is what finds those.
 */
interface DomainEvidence {
  /** What speaks to the area's standing understanding. */
  readonly meaningful: ReadonlyMap<LifeDomainId, Evidence[]>
  /**
   * When anything at all was last heard about an area, momentary readings
   * included.
   *
   * The domain-level backstop reads this rather than `meaningful`, and the
   * difference is a sentence the owner would call wrong. "Nothing has come in
   * about your social life for six weeks" on an evening he has just told the
   * app he is up for company is false in the only sense he cares about. A
   * momentary answer is not an understanding of the area — which is why it does
   * not stop a *standing* concept going stale — and it is certainly the app
   * being spoken to.
   */
  readonly heardAt: ReadonlyMap<LifeDomainId, Instant>
  /**
   * How much of each area is dated after the moment being read — QA-82-011.
   *
   * Skipping future records is right: a reading from next week is not evidence
   * about now, and treating it as current would make an area look fresh on the
   * strength of something that has not happened. What was wrong was the
   * **sentence** that came out of the resulting silence. With the laboratory
   * clock a week back from a fixture's own dates, the app said *"Nothing has
   * ever come in about sleep & recovery"* in the same document that reported
   * five later entries and named their 5–8 April span.
   *
   * Never having been told and not having been told **yet** are different, which
   * is G-009's own rule about a value applied to an area and a moment.
   */
  readonly laterAt: ReadonlyMap<LifeDomainId, number>
  /**
   * Every distinct origin heard about an area, meaningful or momentary.
   *
   * Collected beside `heardAt` rather than derived from `meaningful`, because
   * the sentence this ends up disclosing on — "nothing has come in about career
   * & learning for 3 months" — is about the area's whole silence, and the case
   * it exists for has no meaningful evidence at all: an area whose only record
   * is an imported goal.
   */
  readonly heardSources: ReadonlyMap<LifeDomainId, ReadonlySet<ProvenanceSource>>
}

function evidenceByDomain(view: MemoryView, moment: CoverageMoment): DomainEvidence {
  const out = new Map<LifeDomainId, Evidence[]>()
  const heard = new Map<LifeDomainId, Instant>()
  const later = new Map<LifeDomainId, number>()
  const heardSources = new Map<LifeDomainId, Set<ProvenanceSource>>()
  const addHeard = (domain: LifeDomainId, at: Instant, record: CanonicalRecord): void => {
    const held = heard.get(domain)
    if (held === undefined || at > held) heard.set(domain, at)
    const sources = heardSources.get(domain) ?? new Set<ProvenanceSource>()
    sources.add(evidenceSourceOf(record))
    heardSources.set(domain, sources)
  }
  const add = (domain: LifeDomainId, record: CanonicalRecord, at = record.occurredAt): void => {
    addHeard(domain, at, record)
    const held = out.get(domain)
    const entry: Evidence = {
      at,
      record: record.id,
      source: evidenceSourceOf(record),
    }
    if (held === undefined) out.set(domain, [entry])
    else held.push(entry)
  }

  for (const record of view.history.effective) {
    // A record dated in the future is not evidence about now. Time travel makes
    // this reachable, and treating it as current would make an area look fresh
    // on the strength of something that has not happened.
    //
    // It is counted on the way past, though — QA-82-011. The exclusion is
    // right and the silence it leaves is not the same silence as never having
    // been told, and only something that has seen both can tell them apart.
    if (record.occurredAt > moment.now) {
      for (const domain of record.domains) later.set(domain, (later.get(domain) ?? 0) + 1)
      continue
    }

    if (bearsConcept(record)) {
      const definition = moment.concepts.definitionFor(record.concept)
      /*
       * A context in force is current, whatever its date — D-012.
       *
       * "A context is in force between its `validFrom` and `validUntil`, and
       * that is the whole of its currency." Reading a durable arrangement's age
       * as silence puts two sentences on one screen that contradict each other:
       * the premise says his daughter is here tonight and the line above it
       * says nothing has come in about her for six months. Both came from the
       * same run. That is DEF-0017's class, and the app was on the wrong side
       * of it about the one fact section 8 uses as its example of something
       * that does not need re-asking.
       *
       * Whether he has *done* anything in an area lately is a different
       * question from whether what the app understands about it has aged, and
       * conflating them is how a settled fact starts reading as neglect.
       */
      const inForce =
        record.kind === 'context' &&
        record.validFrom <= moment.now &&
        (record.validUntil === undefined || moment.now < record.validUntil)
      const at = inForce ? moment.now : record.occurredAt
      if (definition.standing === true) add(definition.domain, record, at)
      else addHeard(definition.domain, at, record)
      continue
    }

    const seen = new Set<LifeDomainId>()
    for (const domain of record.domains) {
      if (seen.has(domain)) continue
      seen.add(domain)
      add(domain, record)
    }
  }

  return { meaningful: out, heardAt: heard, laterAt: later, heardSources }
}

/**
 * The distinct origins in a body of evidence, in a stable order.
 *
 * Sorted so that two runs over the same history produce the same array, which
 * is what lets a projection be compared rather than merely rebuilt.
 */
function sourcesOf(evidence: readonly Evidence[]): readonly ProvenanceSource[] {
  return [...new Set(evidence.map((entry) => entry.source))].sort()
}

function latest(evidence: readonly Evidence[]): Evidence | undefined {
  let best: Evidence | undefined
  for (const entry of evidence) if (best === undefined || entry.at > best.at) best = entry
  return best
}

/**
 * Whether this area matters to the owner, on his own evidence.
 *
 * A named entity, a goal, a week pointed here, or anything he has actually
 * done. Note what is not on the list: the number of readings. An area can be
 * important and silent — that is the whole case section 63 is about — so
 * importance is read from commitments and actions rather than from how recently
 * the app was fed.
 */
function mattersToOwner(domain: LifeDomainId, view: MemoryView, moment: CoverageMoment): boolean {
  /*
   * The owner's own entities, not the engine's.
   *
   * `decisionEntities` folds in the four routines the engine provides for
   * itself — sleep, winding down, a walk, easing off (D-021) — and those carry
   * life domains. Reading importance off that list would make sleep and health
   * matter in every history ever loaded, including one containing nothing at
   * all, which is the engine deciding that its own furniture is part of the
   * owner's life.
   */
  for (const entity of view.entities.all()) {
    if (entity.domain === domain) return true
  }
  for (const record of view.history.effective) {
    if (record.occurredAt > moment.now) continue
    if (!record.domains.includes(domain)) continue
    switch (record.kind) {
      case 'goal':
      case 'commitment':
      case 'preference':
      case 'decision':
      case 'action-recommendation':
      case 'action-start':
      case 'action-completion':
      case 'action-decline':
      case 'action-unable-now':
      case 'outcome':
      case 'domain-update':
      case 'coverage-update':
      case 'relationship-event':
        return true
      default:
        break
    }
  }
  return false
}

// ---------------------------------------------------------------------------

function strengthFor(
  concepts: readonly ConceptCoverage[],
  daysSince: number | undefined,
): EvidenceStrength {
  if (daysSince === undefined) return 'none'
  const held = concepts.filter(
    (entry) => entry.state === 'explicit' || entry.state === 'inferred',
  ).length
  if (held >= 2) return 'strong'
  if (held === 1) return 'moderate'
  return 'weak'
}

function describe(
  label: string,
  status: CoverageStatus,
  daysSince: number | undefined,
  later: number,
): string {
  switch (status) {
    case 'current':
      /*
       * QA-C7, and the same class as QA-M1 below.
       *
       * This used to say "is current", which reads as *what the app believes
       * about this area is up to date* — and the app was saying it directly
       * above a belief it had itself marked out of date. `current` means
       * something has come in recently, or a standing concept is held. Those
       * are two different facts about two different things, and the honest
       * sentence is the one about intake, in the app's own voice (DEF-0012).
       */
      return `Something has come in about ${label.toLowerCase()} recently.`
    case 'quiet':
      /*
       * QA-M1. This used to say "and nothing here has gone out of date" — a
       * claim about every reading in the domain. `quiet` only means no
       * *standing* concept has gone past its neglect threshold and the
       * domain is not `goneQuiet` either (D-061); a concept can still be
       * individually `stale` in the fact layer well before it crosses that
       * threshold, since neglect is three times a concept's own freshness
       * window (`NEGLECT_MULTIPLE`), floored at a week. A domain page shows
       * both this sentence and a concept's own "out of date" tag on one
       * screen, and the two are answering different questions — this one is
       * about whether the *domain* needs the owner's attention, not whether
       * every fact in it is still within its own window.
       */
      return `${label} has been quiet, without anything here needing your attention.`
    case 'unheard':
      /*
       * "Ever" is a claim about the whole record, and this state is a reading
       * of one moment — QA-82-011.
       *
       * A history dated after the moment being read leaves exactly the same
       * silence here as a history that was never written, and the app said the
       * same absolute thing about both. Saying which one it is costs a clause
       * and stops the document contradicting its own record span.
       */
      return later > 0
        ? `Nothing has come in about ${label.toLowerCase()} at this point. ${countOf(later, 'entry', 'entries')} here ${later === 1 ? 'is' : 'are'} later than it.`
        : `Nothing has ever come in about ${label.toLowerCase()}.`
    case 'stale':
      // About the app's knowledge, in the app's own voice. Not a claim about
      // how the owner has been living — DEF-0012's rule, on the one kind of
      // sentence that genuinely is about what the app can and cannot see.
      return daysSince === undefined
        ? `Nothing recent has come in about ${label.toLowerCase()}.`
        : `Nothing has come in about ${label.toLowerCase()} for ${describeDays(daysSince)}.`
  }
}

export function describeDays(days: number): string {
  const whole = Math.round(days)
  if (whole <= 1) return 'a day'
  if (whole < 14) return `${whole} days`
  const weeks = Math.round(whole / 7)
  if (weeks < 9) return `${weeks} weeks`
  const months = Math.round(whole / 30)
  return months <= 1 ? 'over a month' : `${months} months`
}

/**
 * Which of the five routes section 8 would take to refresh this area.
 *
 * Read strictly in the plan's order, and the order is the point: asking is the
 * fourth choice, not the first, and "needs update in Life" is what is left when
 * the app has nothing better — which is the state section 8 is trying to make
 * rare rather than the state it is trying to reach.
 */
function routeFor(
  status: CoverageStatus,
  concepts: readonly ConceptCoverage[],
  evidenceComing: boolean,
  canAct: boolean,
): RefreshRoute {
  if (status === 'current' || status === 'quiet') return 'already-current'
  if (evidenceComing) return 'normal-life'
  /*
   * `canAct`, not "there is something named in this area" — QA-82-014, D-155.
   *
   * This used to ask whether the domain had any entity at all, and that is not
   * the question the generator answers. `candidates.ts` needs a move for the
   * *domain* and a subject of that move's own *kind*, and it has three: a place
   * in Home, a learning topic in Career, a financial goal in Money. Health,
   * Social and Fatherhood have none and are not going to get one, because a
   * quiet fortnight is not evidence of capacity or of social energy (DEF-0006).
   *
   * So the app told the owner it would bring Social back on its own, and then
   * had nothing to bring.
   */
  if (canAct) return 'an-action'
  /*
   * `askable`, without `neglected` beside it — QA-82-015, D-156.
   *
   * The round 9 note here claimed `askable` was "the guide's own answer". It is
   * not, and saying so was the reason this went another round: `askable` is
   * `worthAsking` from the fact layer, which is the same gate the question
   * layer opens with — but it was being read through `neglected`, and that is a
   * claim about a *standing* fact whose last answer has lapsed.
   *
   * `energy.current` is not a standing fact. It can never be `neglected`, so
   * this test could never be true of it, so an area whose only route back was a
   * question about tonight's energy fell to `needs-review` and Life said nothing
   * the app could do would bring it back — while Now was already asking exactly
   * that question, one tap from making the area current.
   *
   * `questionFor` rather than `askable` alone, because `askable` says the fact
   * layer would spend a question here and the catalogue is what decides whether
   * one exists. The guide gives up at `questionFor(...) === undefined`; a route
   * that did not ask the same thing would promise past it, which is D-155.
   */
  if (concepts.some((entry) => entry.askable && questionFor(entry.concept) !== undefined)) {
    return 'a-question'
  }
  return 'needs-review'
}

/**
 * The domains an action could actually refresh, right now, in this history.
 *
 * Everything that gates `coverageCandidates` is asked here, so the route cannot
 * promise past the generator: the move must exist for the domain, a subject of
 * that move's kind must exist in it, and the domain must be one the app is
 * allowed to raise of its own accord. Private / Sexual Health is manual-entry
 * first (section 11) and is never raised, so an action is not the route by
 * which it comes back — it is covered and reported on Life like any other area.
 */
function domainsAnActionCouldRefresh(
  entities: EntityIndex,
  domains: DomainRegistry,
): ReadonlySet<LifeDomainId> {
  const named = new Map<LifeDomainId, Set<SemanticEntity['kind']>>()
  for (const entity of entities.all()) {
    const kinds = named.get(entity.domain)
    if (kinds === undefined) named.set(entity.domain, new Set([entity.kind]))
    else kinds.add(entity.kind)
  }

  const out = new Set<LifeDomainId>()
  for (const domain of domains.all()) {
    if (!mayRaiseUnasked(domains.defaultPrivacyFor(domain.id))) continue
    const move = refreshingMoveFor(domain.id)
    if (move === undefined) continue
    if (named.get(domain.id)?.has(move.kind) !== true) continue
    out.add(domain.id)
  }
  return out
}

/**
 * Domains where an answer is already on its way without anyone being asked.
 *
 * Section 8's first preference. An episode the owner **finished**, whose result
 * window is still open, is evidence about that area arriving on its own — and
 * from Phase 4 the morning-after sleep matcher can answer some of those without
 * a tap at all.
 *
 * **The window is asked for rather than guessed at — QA-82-016, D-156.** This
 * read the history for an `action-completion` *or an `action-start`* in the last
 * two days, and a start is not a finish. `outcomeWindowFor` returns nothing
 * until the episode is `completed`, and says so in its own words: a move that
 * was started and never finished "is still a lifecycle question — Now already
 * has the buttons for it". So the owner pressed **Start it**, went no further,
 * and Life told him an answer was already on its way for something he might
 * never do.
 *
 * Asking `outcomeWindowFor` fixes the two-day guess as well. The result window
 * is the outcome layer's to define — next morning for some verbs, a fixed delay
 * for others — and a second copy of it here would be the same defect in a
 * slower-moving form.
 */
function domainsWithEvidenceComing(
  view: MemoryView,
  moment: CoverageMoment,
): ReadonlySet<LifeDomainId> {
  const out = new Set<LifeDomainId>()
  for (const episode of collectEpisodes(view, moment.zone)) {
    const window = outcomeWindowFor(episode, moment.zone)
    // Nothing to wait for, or the moment for asking has already passed.
    if (window === undefined || moment.now > window.latest) continue
    out.add(episode.semantics.domain)
  }
  return out
}

export function assembleCoverage(
  view: MemoryView,
  entities: EntityIndex,
  moment: CoverageMoment,
): CoverageState {
  const { meaningful, heardAt, laterAt, heardSources } = evidenceByDomain(view, moment)
  const coming = domainsWithEvidenceComing(view, moment)
  const today = localDayIdAt(moment.now, moment.zone)

  const conceptsByDomain = new Map<LifeDomainId, ConceptDefinition[]>()
  for (const definition of moment.concepts.all()) {
    /*
     * A conclusion is not something the owner can be neglecting — QA-82-001.
     *
     * Nothing ever writes a record for a derived concept, so measuring how long
     * it has been since one would report permanent neglect of a fact he has no
     * way to supply, and start prodding him about it. That is DEF-0015's
     * failure arriving from a new direction, and the comment below about a
     * settled custody arrangement is the same warning from the other side.
     */
    if (definition.derived === true) continue
    const held = conceptsByDomain.get(definition.domain)
    if (held === undefined) conceptsByDomain.set(definition.domain, [definition])
    else held.push(definition)
  }

  const canAct = domainsAnActionCouldRefresh(entities, moment.domains)

  const domains: DomainCoverage[] = []

  for (const domain of moment.domains.all()) {
    const matters = mattersToOwner(domain.id, view, moment)
    const evidence = meaningful.get(domain.id) ?? []
    const newest = latest(evidence)
    const daysSinceEvidence =
      newest === undefined
        ? undefined
        : Math.max(0, localDaysBetween(localDayIdAt(newest.at, moment.zone), today))

    const heard = heardAt.get(domain.id)
    const laterHere = laterAt.get(domain.id) ?? 0
    const daysSinceHeard =
      heard === undefined
        ? undefined
        : Math.max(0, localDaysBetween(localDayIdAt(heard, moment.zone), today))

    const conceptRows: ConceptCoverage[] = []
    for (const definition of conceptsByDomain.get(domain.id) ?? []) {
      const entry = view.facts.get(definition.id)
      const knowledge = entry?.knowledge
      const observedAt =
        knowledge === undefined || knowledge.state === 'unknown' ? undefined : knowledge.observedAt
      /*
       * Coverage never contradicts the fact layer.
       *
       * If a concept resolves to a usable value right now, it is covered — and
       * how long ago the record was written is beside the point, because the
       * concept's own freshness horizon has already had that argument. This
       * matters most where it looks wrong: a custody arrangement settled a year
       * ago answers "is she with you" today, and `childPresent` reads explicit
       * because of it. Measuring that concept's age without asking the fact
       * layer first would call a settled arrangement neglect and start prodding
       * the owner about it — DEF-0015's failure, arriving from a new direction.
       */
      const held = knowledge?.state === 'explicit' || knowledge?.state === 'inferred'
      const daysSince =
        observedAt === undefined
          ? undefined
          : Math.max(0, localDaysBetween(localDayIdAt(observedAt, moment.zone), today))
      /*
       * A concept with no entry at all is one nothing has ever spoken to.
       *
       * `resolveFacts` seeds every concept the owner can answer, so this does
       * not happen today; saying it here rather than leaving a surface to
       * invent a sentence for the case is the point. Every path that has no
       * evidence now arrives carrying the reason it has none.
       */
      const whyUnknown: Unknown | undefined =
        knowledge === undefined
          ? unknown('never-observed')
          : knowledge.state === 'unknown'
            ? knowledge
            : undefined
      const neglectedAfter = neglectedAfterDaysFor(definition.freshness)
      const source =
        observedAt === undefined ? undefined : sourceOfNewest(definition.id, view, moment)

      conceptRows.push({
        concept: definition.id,
        label: definition.label,
        domain: definition.domain,
        privacy: definition.privacy,
        state: knowledge?.state ?? 'unknown',
        unknown: whyUnknown,
        standing: definition.standing === true,
        source,
        sources: sourcesOf(
          (entry?.considered ?? []).flatMap((id) => {
            const record = view.history.byId(id)
            return record === undefined
              ? []
              : [{ at: record.occurredAt, record: id, source: evidenceSourceOf(record) }]
          }),
        ),
        lastEvidenceAt: observedAt,
        daysSince,
        neglectedAfterDays: neglectedAfter,
        // Never observed at all is not neglect either. Nobody has let anything
        // lapse; the owner simply has not mentioned it, and an app that treated
        // the two the same would nag about a life area he has never raised.
        // `daysSince` is undefined in that case, which is what says so.
        neglected:
          matters &&
          definition.standing === true &&
          !held &&
          neglectedAfter !== undefined &&
          daysSince !== undefined &&
          daysSince >= neglectedAfter,
        askable: entry?.worthAsking === true,
        evidence: entry?.considered ?? [],
      })
    }

    const standing = conceptRows.filter((entry) => entry.standing)
    const anyNeglected = standing.some((entry) => entry.neglected)
    const anyHeld = standing.some(
      (entry) => entry.state === 'explicit' || entry.state === 'inferred',
    )

    /*
     * Four states, and the two that look alike are the important pair.
     *
     * `unheard` is a domain the owner has never spoken about. `stale` is one he
     * has, and where what the app knows has aged out. G-009's rule applied to
     * an area: those are different, and the app owes him a signal about the
     * second and silence about the first.
     *
     * The second stale branch catches an area with no standing concept at all —
     * social has one momentary reading and nothing else — where the only
     * evidence is what he has done. Four weeks of nothing in an area he has
     * shown matters to him is section 63 whatever the registry does or does not
     * track about it.
     */
    const goneQuiet = matters && daysSinceHeard !== undefined && daysSinceHeard >= DOMAIN_QUIET_DAYS

    const status: CoverageStatus =
      heard === undefined
        ? 'unheard'
        : anyNeglected || goneQuiet
          ? 'stale'
          : anyHeld || daysSinceHeard === undefined || daysSinceHeard < NEGLECT_FLOOR_DAYS
            ? 'current'
            : 'quiet'

    const weakest = pickWeakest(standing)

    // The age the summary quotes is the age of the thing that is actually
    // overdue. Quoting the domain's newest record while the sub-area behind the
    // judgement is three weeks older would put a sentence on screen that is
    // true of neither.
    const staleFor = weakest?.daysSince ?? daysSinceEvidence

    domains.push({
      domain: domain.id,
      label: domain.label,
      status,
      strength: strengthFor(standing, daysSinceEvidence),
      matters,
      lastEvidenceAt: newest?.at,
      daysSinceEvidence,
      later: laterHere,
      daysSinceHeard,
      source: newest?.source,
      /*
       * Everything heard about this area, not only what counted as meaningful.
       * The overview's sentence is about the area's silence as a whole, so the
       * disclosure has to be about the same body of evidence the sentence is.
       */
      sources: [...(heardSources.get(domain.id) ?? new Set<ProvenanceSource>())].sort(),
      concepts: conceptRows,
      weakest,
      refresh: routeFor(status, conceptRows, coming.has(domain.id), canAct.has(domain.id)),
      summary: describe(domain.label, status, staleFor ?? daysSinceHeard, laterHere),
    })
  }

  const neglected = domains.filter((entry) => entry.status === 'stale' && entry.matters)
  const raisable = neglected.filter((entry) =>
    mayRaiseUnasked(moment.domains.defaultPrivacyFor(entry.domain)),
  )

  // The longest silence wins, and a tie is settled by the registry's own order
  // so that the same history reports the same area on every device.
  let mostNeglected: DomainCoverage | undefined
  for (const entry of raisable) {
    if (mostNeglected === undefined) {
      mostNeglected = entry
      continue
    }
    const mine = entry.daysSinceEvidence ?? 0
    const theirs = mostNeglected.daysSinceEvidence ?? 0
    if (mine > theirs) mostNeglected = entry
  }

  const byId = new Map(domains.map((entry) => [entry.domain, entry]))
  return {
    domains,
    get: (domain) => byId.get(domain),
    neglected,
    mostNeglected,
  }
}

/** The sub-area a refresh should aim at: the most overdue one that matters. */
function pickWeakest(concepts: readonly ConceptCoverage[]): ConceptCoverage | undefined {
  let best: ConceptCoverage | undefined
  let bestOverdue = 0
  for (const entry of concepts) {
    if (!entry.neglected) continue
    if (entry.daysSince === undefined || entry.neglectedAfterDays === undefined) continue
    const overdue = entry.daysSince / entry.neglectedAfterDays
    if (best === undefined || overdue > bestOverdue) {
      best = entry
      bestOverdue = overdue
    }
  }
  return best
}

/** Where the newest record about one concept came from. */
function sourceOfNewest(
  concept: ConceptId,
  view: MemoryView,
  moment: CoverageMoment,
): ProvenanceSource | undefined {
  let best: { at: Instant; source: ProvenanceSource } | undefined
  for (const record of view.history.effective) {
    if (!bearsConcept(record)) continue
    if (record.concept !== concept) continue
    if (record.occurredAt > moment.now) continue
    if (best === undefined || record.occurredAt > best.at) {
      best = { at: record.occurredAt, source: evidenceSourceOf(record) }
    }
  }
  return best?.source
}
