import { createRecordFactory } from '../domain/build'
import { CONCEPT } from '../domain/concepts'
import { derivedRecordId, type RecordId } from '../domain/ids'
import { bearsConcept, type OutcomeRecord, type Provenance } from '../domain/records'
import type { Instant, TimeZoneId } from '../domain/time'
import type { ConceptId } from '../domain/windows'
import type { MemoryView } from '../memory/view'
import { collectEpisodes, type Episode } from './lifecycle'
import { profileFor } from './moves'
import { answeredAspects, outcomeWindowFor, readingAwaitedBy, EFFECT_STEPS } from './outcomes'
import { SLEEP_BASELINE_HOURS } from './situation'
import { hoursValue } from './values'

/**
 * Evidence normal life already produces (canonical plan section 8).
 *
 * Section 8 puts "use trustworthy evidence already being generated by normal
 * life" **first** in its order of preference and "ask one small question"
 * fourth, and there is a case where the app was plainly doing the fourth thing
 * when it could do the first: the morning after an early night, the guide asks
 * how much sleep he got, and then a separate card asks how much the early night
 * did for his sleep. The second question is the first one again, asked worse —
 * the owner has already given the app the answer, in a number, and is being
 * made to grade it as well.
 *
 * So the morning reading becomes the outcome.
 *
 * ## Four rules the owner set before any of this was allowed
 *
 * **1. It never opens a loop, only closes one.** `outcomeWindowFor` returns
 * nothing unless the episode is `completed`, and this reads that function
 * rather than reimplementing its condition. A wind-down that was started and
 * never marked done, followed by eight hours of sleep, produces nothing at all:
 * **the app does not know he did it**, and a later result is not evidence that
 * an earlier action occurred. Inference completes; it never assumes.
 *
 * **2. It never masquerades as something he said.** The record's provenance
 * says `derived` and says which reading it came from. Nothing here writes
 * `owner`, and reliability — however high — cannot change that: D-014's four
 * states exist so an inference stays legible as one.
 *
 * **3. It is worth what a derived reading of *sleep hours* is worth**, which
 * the concept registry sets at 0.8 — high, and lower than the owner's own
 * answer at 1.0. The reading itself is excellent: a measured or reported
 * duration. What is assumed is the **attribution** — that the night went the
 * way it did partly because of the wind-down — and that assumption is the
 * discount. Roughly, five derived mornings weigh what four tapped answers
 * weigh. Note that the number is about sleep hours and not about derivation:
 * the same machinery pointed at how the owner *feels* would be worth 0.4,
 * because the registry says a derived reading of that is a much weaker thing.
 *
 * **4. It writes the ordinary outcome record**, with the same aspect, the same
 * `about`, the same observation scale. There is no second outcome path and no
 * second learner — `learning.ts` reads this exactly as it reads a tap, because
 * its four questions never ask where a record came from.
 *
 * ## And it may never conclude harm
 *
 * The effect scale has four levels and this matcher can produce three. A short
 * night after a wind-down is a short night; it is not evidence that winding
 * down **backfired**, which is a claim about causation that a number cannot
 * support and only the owner can make. Leaving `harm` to him is the same
 * discipline as D-038: an app may not assert from what it can see alone.
 */

export const DERIVED_SLEEP_PROVENANCE: Provenance = {
  source: 'derived',
  writtenBy: 'sleep-outcome',
  note: 'read off the next morning’s sleep reading rather than asked for',
}

/**
 * What a night is worth as an answer to "how much did this do for your sleep?".
 *
 * Absolute rather than compared to his usual, which is D-056 read literally:
 * effect answers are absolute levels, and the delta model was worked through
 * and withdrawn because a move that consistently does nothing would keep its
 * prior forever. The reference point is `SLEEP_BASELINE_HOURS`, the same
 * working baseline the rest of the engine uses, so there is one number to argue
 * with rather than two.
 *
 * - a full night, at or above the baseline — the move did what it is for;
 * - within an hour of it — a decent night, short of what was wanted;
 * - anything less — the night was short, and that is not much of a result.
 */
const A_DECENT_NIGHT = SLEEP_BASELINE_HOURS - 1

/** Steps on the effect scale: 3 real, 2 some, 1 not much, 0 backfired. */
function effectStepForSleep(hours: number): 3 | 2 | 1 {
  if (hours >= SLEEP_BASELINE_HOURS) return 3
  if (hours >= A_DECENT_NIGHT) return 2
  return 1
}

const SENTIMENT: Record<3 | 2 | 1, 'better' | 'same'> = { 3: 'better', 2: 'better', 1: 'same' }

export interface DerivedOutcome {
  readonly record: OutcomeRecord
  readonly episode: Episode
  /** The sleep reading this was read off, so the trace can point at it. */
  readonly from: RecordId
  readonly hours: number
  /** One line for the inspector, in ordinary words. */
  readonly because: string
}

/**
 * A sleep reading belonging to the morning that judges this episode.
 *
 * The window comes from `outcomeWindowFor`, which for a next-morning move runs
 * from five o'clock to the end of that owner-local day. A reading recorded the
 * evening before cannot be about a night that has not happened, and one from
 * two days later is about a different night.
 */
function morningReadingFor(
  episode: Episode,
  view: MemoryView,
  moment: DeriveMoment,
): { readonly hours: number; readonly record: RecordId; readonly at: Instant } | undefined {
  const window = outcomeWindowFor(episode, moment.zone)
  if (window === undefined) return undefined

  let best: { hours: number; record: RecordId; at: Instant } | undefined
  for (const record of view.history.effective) {
    if (!bearsConcept(record)) continue
    if (record.concept !== CONCEPT.sleepHours) continue
    // Nothing is derived from a reading that has not happened yet. Time travel
    // makes that reachable, and an outcome read off a future night would be an
    // answer about a morning nobody has had.
    if (record.occurredAt > moment.now) continue
    if (record.occurredAt < window.earliest || record.occurredAt > window.latest) continue
    const hours = hoursValue(record.value)
    if (hours === undefined) continue
    if (best === undefined || record.occurredAt < best.at) {
      best = { hours, record: record.id, at: record.occurredAt }
    }
  }

  return best
}

export interface DeriveMoment {
  readonly now: Instant
  readonly zone: TimeZoneId
}

/**
 * Outcome records the history already implies, ready to append.
 *
 * Pure: it reads and returns records, and whether they are written is the
 * surface's business — the same division as `planLifecycle`. The ids are
 * derived from the episode and the aspect, so running this twice produces
 * byte-identical records and the store's existing idempotency skips the second
 * (D-015). That mechanism was built so an import could be re-run; this is the
 * same problem arriving from a third direction.
 */
export function deriveOutcomes(view: MemoryView, moment: DeriveMoment): readonly DerivedOutcome[] {
  const out: DerivedOutcome[] = []
  const build = createRecordFactory({
    zone: moment.zone,
    provenance: DERIVED_SLEEP_PROVENANCE,
  })

  for (const episode of collectEpisodes(view, moment.zone)) {
    const profile = profileFor(episode.semantics.target.verb)
    // Only moves whose outcome is a reading of sleep hours, judged in the
    // morning. The pairing is read off the profile rather than a list of verbs
    // here, so a sixteenth restorative verb is covered the moment it exists.
    if (profile.measures !== CONCEPT.sleepHours) continue
    if (profile.outcome.when !== 'next-morning') continue
    if (!profile.aspects.includes('effect')) continue
    if (answeredAspects(episode).has('effect')) continue

    const reading = morningReadingFor(episode, view, moment)
    if (reading === undefined) continue

    const step = effectStepForSleep(reading.hours)
    const record = build(
      'outcome',
      {
        /*
         * The morning it is about, not the moment it was worked out.
         *
         * That is the honest reading of `occurredAt` — the effect happened
         * overnight — and it is also what makes this record a pure function of
         * the history. If it carried the moment of derivation, opening the app
         * an hour later would produce a *different* record wearing the same
         * derived id, and the store would rightly refuse it (D-015). As it
         * stands, deriving twice produces the identical row and the second
         * append is a no-op, whichever day it happens on.
         */
        occurredAt: reading.at,
        id: derivedRecordId('derived-outcome', episode.recommendation, 'effect'),
        domains: [episode.semantics.domain],
        entities: [episode.semantics.subject, episode.semantics.target.object],
      },
      {
        about: episode.recommendation,
        aspect: 'effect',
        observation: { type: 'scale', value: step, of: EFFECT_STEPS },
        sentiment: SENTIMENT[step],
      },
    )

    out.push({
      record,
      episode,
      from: reading.record,
      hours: reading.hours,
      because: `read off ${reading.hours} hours of sleep the next morning rather than asked for`,
    })
  }

  return out
}

/** Just the records, for a surface that only wants to append them. */
export function derivedOutcomeRecords(
  view: MemoryView,
  moment: DeriveMoment,
): readonly OutcomeRecord[] {
  return deriveOutcomes(view, moment).map((derived) => derived.record)
}

/**
 * Readings a due result is currently waiting on.
 *
 * The guide reads this and asks for the reading rather than for a verdict; the
 * outcome card holds its own question back for the same episodes. Between them
 * that is one question in place of another rather than one more, which is the
 * only shape section 12 leaves room for.
 *
 * Ordered by when the window opened, so a backlog is worked through oldest
 * first — the same order the owner remembers it in.
 */
export function awaitedReadings(view: MemoryView, moment: DeriveMoment): readonly ConceptId[] {
  const found: { readonly concept: ConceptId; readonly at: Instant }[] = []

  for (const episode of collectEpisodes(view, moment.zone)) {
    const window = outcomeWindowFor(episode, moment.zone)
    if (window === undefined) continue
    if (moment.now < window.earliest || moment.now > window.latest) continue
    if (answeredAspects(episode).has('effect')) continue
    const concept = readingAwaitedBy(episode, view, moment.zone)
    if (concept === undefined) continue
    found.push({ concept, at: window.earliest })
  }

  found.sort((a, b) => a.at - b.at)
  return [...new Set(found.map((entry) => entry.concept))]
}
