import { useState, type ReactNode } from 'react'
import { ObjectKind, Panel, UnknownSet, type ObjectKindName } from '../../components/ui'
import type { LifeDomainId } from '../../domain/domains'
import type { EntityRef } from '../../domain/entities'
import { permissionDefinition } from '../../domain/privacy'
import { correctionConsequence, type CorrectionGesture } from '../../intelligence/corrections'
import {
  AUTHORABLE_KINDS,
  dayFromInput,
  milestoneConfirmation,
  minutesFromClock,
  proposeAuthoring,
  PROVING_DOMAINS,
  type AuthorableKind,
  type AuthoringDraft,
  type DestinationDraft,
} from '../../intelligence/authoring'
import {
  describeOffer,
  describeReading,
  proposeInterpretedDestination,
  readAimIn,
  type AimReading,
} from '../../intelligence/interpret'
import type { CourseReflection } from '../../intelligence/progress'
import type { ProgressEvidence } from '../../domain/progress'
import type { OutcomeAnswer } from '../../intelligence/outcomes'
import type { BlockerDecision } from '../../intelligence/blockers'
import type { Situation } from '../../intelligence/situation'
import type {
  CorrectableEvent,
  DomainDestination,
  DomainPageData,
  StandingBlocker,
} from './domainPages'

/**
 * The panels routing 84 adds to a domain page.
 *
 * Presentational only, and deliberately so: **no function in this file builds a
 * record**. Every handler is passed down from `DomainPage.tsx`, which is where
 * the builders are called and therefore where the ordinary-use instrument's
 * route table finds them (`tests/synthetic/journey.ts`). Splitting the markup
 * out keeps one screen's worth of controls readable without moving a single
 * control off that screen.
 *
 * Two rules hold across everything below, and both are enforced elsewhere and
 * honoured here.
 *
 * **Every input has a name and says what the answer is for** — D-176. A
 * `<label>` that points at the control, and a note in view while he types
 * saying what the app will do with it. `architecture-guards.test.ts` fails the
 * build without the first; the second is the half a checker cannot see and the
 * half E13 recorded the owner needing.
 *
 * **Nothing here shows a number about him** — D-162. No percentage, no share,
 * no bar, no readiness figure, about the owner or about Adaya. A phase whose
 * whole subject is progress is where one arrives looking reasonable, so the
 * counts that do appear are counts of things that happened, generated by
 * `domain/progress.ts` from the evidence behind them.
 */

// ---------------------------------------------------------------------------
// What the owner is trying to become — F01, F35, package 1
// ---------------------------------------------------------------------------

/**
 * Where a destination may be named — the adjudication's proving scope.
 *
 * Career, Health and Money, and **not Fatherhood**: *"the growth model is the
 * product's best-evidenced mechanism, Phases 81 and 82 each corrected it, and
 * it is the hardest place to prove a new object and the worst place to break
 * one. It joins once the shape is proved."*
 *
 * The panel is absent on the other pages rather than empty. An empty one would
 * be the app inviting him to fill in something it is not ready to hold, and
 * every domain page in this product is a report before it is a form.
 */
/**
 * One named part of a destination, said or not said — G-009.
 *
 * The whole reason this is a component: *"stated"* has to change how the row
 * **reads**, not merely whether it is there. Two rows of identical grey, one
 * carrying the owner's own sentence and one carrying the app's admission that
 * it has none, is a page that tells him nothing he could not have worked out.
 *
 * What changes is the value's weight, and nothing else. An unstated part is not
 * struck through, greyed to unreadable, coloured, badged or counted — it is
 * quieter, which is what "the owner has not said this" should look like beside
 * something he did say.
 */
function DestinationPart({
  label,
  stated,
  testId,
  children,
}: {
  label: string
  stated: boolean
  testId: string
  children: ReactNode
}) {
  return (
    <div className="destination__part" data-stated={stated ? 'yes' : 'no'}>
      <dt className="destination__label">{label}</dt>
      <dd className="destination__value" data-testid={testId}>
        {children}
      </dd>
    </div>
  )
}

export function DestinationPanel({
  data,
  situation,
  area,
  disabled,
  onName,
  onRevise,
  onMilestone,
  onWithdrawReading,
  onAcceptReading,
}: {
  data: DomainPageData
  situation: Situation
  area: string
  disabled: boolean
  onName: (draft: DestinationDraft, reading?: AimReading) => void
  onRevise: (
    destination: DomainDestination,
    changes: { baseline?: string; evidence?: readonly string[]; unknowns?: readonly string[] },
  ) => void
  onMilestone: (destination: DomainDestination, statement: string) => void
  onWithdrawReading: (destination: DomainDestination) => void
  onAcceptReading: (destination: DomainDestination, reading: AimReading, into: LifeDomainId) => void
}) {
  const [naming, setNaming] = useState(false)
  const [aim, setAim] = useState('')
  const [milestone, setMilestone] = useState('')
  const [filling, setFilling] = useState<string | undefined>(undefined)
  const [draft, setDraft] = useState('')
  /** Where he has chosen to file it; undefined is *where this page is*. */
  const [fileIn, setFileIn] = useState<LifeDomainId | undefined>(undefined)
  /** Whether he has answered the scope question, as against not yet. */
  const [answeredScope, setAnsweredScope] = useState(false)
  /** The destination whose reading gesture is showing its consequence. */
  const [deciding, setDeciding] = useState<string | undefined>(undefined)

  /*
   * Three proving domains, not twelve.
   *
   * A destination already recorded is always shown — an area that gained one
   * before this rule, or through an import, must not have it silently hidden —
   * and the control that makes a new one is offered only where the object is
   * proved.
   */
  const proving = PROVING_DOMAINS.includes(data.page.domains[0]!)

  /*
   * The same reading the discovery card makes, on the other surface that takes
   * an aspiration — routing 91.
   *
   * One interpreter and two callers rather than one interpreter and one
   * caller, because QA-83-003's second finding is that two screens reaching one
   * builder are two controls: a seam built on only one of them is a seam the
   * owner falls through the first time he uses the other.
   */
  const here = data.page.domains[0]!
  const reading = aim.trim() === '' ? undefined : readAimIn(aim.trim(), here, situation)
  // Any candidate the question is between, not only the single settled offer.
  const filedIn =
    fileIn !== undefined && (reading?.candidates ?? []).includes(fileIn) ? fileIn : undefined
  const label = (id: LifeDomainId) => situation.domains.labelFor(id)
  const offer = reading === undefined ? undefined : describeOffer(reading, label)
  const readingLine = reading === undefined ? undefined : describeReading(reading, label)
  const proposal =
    reading === undefined
      ? undefined
      : proposeInterpretedDestination(
          { aim: aim.trim(), domain: filedIn ?? here },
          reading,
          situation,
        )

  if (!proving && data.destinations.length === 0) return null

  return (
    <Panel title="What you are aiming at">
      {data.destinations.length === 0 ? (
        <p className="note" data-testid="destination-empty">
          Nothing here says what {area} is for. That is the one thing the app cannot work out on its
          own.
        </p>
      ) : null}

      {data.destinations.map((entry) => (
        <div key={entry.destination.source} className="destination" data-testid="destination">
          <ObjectKind kind="destination" />
          <p className="destination__aim" data-testid="destination-aim">
            {entry.reading.aim}
          </p>

          {/*
            Four parts, always four rows — routing 90, package 90.2, G-009.

            An unstated part used to be left out of the list and named in a
            footnote underneath. Everything about that was true and it read as a
            *shorter destination*: the owner saw two rows, no gap, and a
            sentence at the bottom he had to join up himself. Here the row is
            drawn either way and an unstated one says so where the answer would
            have been.

            **It is a row, not a slot.** There is no count, no "2 of 4", no bar
            and no order — `stated` is four booleans with no length precisely so
            that nothing on this surface can add them up. A destination with one
            part filled in is not a quarter of a destination (D-162, section 22).
          */}
          <dl className="destination__parts">
            <DestinationPart
              label="Where you are"
              stated={entry.reading.stated.baseline}
              testId="destination-baseline"
            >
              {entry.reading.baseline}
            </DestinationPart>
            <DestinationPart
              label="Next"
              stated={entry.reading.stated.next}
              testId="destination-next"
            >
              {entry.reading.next}
            </DestinationPart>
            <DestinationPart
              label="What would count"
              stated={entry.reading.stated.evidence}
              testId="destination-evidence"
            >
              <ul className="destination__list">
                {entry.reading.evidence.map((line) => (
                  <li key={line}>{line}</li>
                ))}
              </ul>
            </DestinationPart>
            <DestinationPart
              label="Not sure about"
              stated={entry.reading.stated.unknowns}
              testId="destination-unknowns"
            >
              <ul className="destination__list">
                {entry.reading.unknowns.map((line) => (
                  <li key={line}>{line}</li>
                ))}
              </ul>
            </DestinationPart>
          </dl>

          {entry.destination.milestones.length === 0 ? null : (
            <ul className="milestones" data-testid="destination-milestones">
              {entry.destination.milestones.map((milestone) => (
                <li
                  key={milestone.goal.source}
                  className="milestone"
                  data-reached={milestone.reached ? 'yes' : 'no'}
                >
                  <ObjectKind kind="milestone" />
                  <span className="milestone__name">{milestone.goal.statement}</span>
                  {/*
                    Three words, and they are three different facts — gate item 2.

                    "Reached" is the owner having said so on this milestone.
                    It is not a session having happened and it is not a course
                    having finished; both of those are counted separately, under
                    their own names, in the panel below.

                    `data-reached` styles the state and carries no colour that
                    ranks it: reached is *settled*, not *better*, so it reads as
                    a completed sentence rather than as a win.
                  */}
                  {/*
                    Three states, because there are three — QA-91-005.

                    "Reached" is the owner having said so. "Still ahead" is a
                    step the app is still suggesting. A step **set aside** when
                    the aim moved areas is neither, and calling it *still ahead*
                    was the screen contradicting an engine that had stopped
                    proposing it. It says why it was set aside, because a state
                    without its cause is the app asking to be trusted (D-143).
                  */}
                  <span className="milestone__state">
                    {milestone.reached
                      ? 'reached — you said so'
                      : milestone.setAside
                        ? 'set aside — the aim moved'
                        : 'still ahead'}
                  </span>
                </li>
              ))}
            </ul>
          )}

          {/*
            What the **app** does not know, said once — routing 84, kept.

            The four rows above say what the *owner* has not filled in, in the
            place each answer would go. This is a different sentence with a
            different subject: the app's own admission about the limits of what
            it holds, which is what a surface whose job is to say what it
            understands owes the person reading it.

            Routing 90 re-typeset this object and briefly dropped this line as
            redundant. It is not redundant and, more to the point, removing it
            would have been a **product** change made by a visual phase — the
            one thing this phase was told not to do.
          */}
          {entry.reading.missing.length === 0 ? null : (
            <p className="note" data-testid="destination-missing">
              The app does not know {entry.reading.missing.join(', ')}.
            </p>
          )}

          <ReadingRow
            entry={entry}
            situation={situation}
            disabled={disabled}
            deciding={deciding === entry.destination.source}
            onDecide={(open) => setDeciding(open ? entry.destination.source : undefined)}
            onWithdrawReading={onWithdrawReading}
            onAcceptReading={onAcceptReading}
          />

          {filling === entry.destination.source ? (
            <div className="domain-correction">
              <label
                className="domain-correction__prompt"
                htmlFor={`destination-fill-${entry.destination.source}`}
              >
                {promptFor(entry)}
              </label>
              <p className="note">{noteFor(entry)}</p>
              <input
                id={`destination-fill-${entry.destination.source}`}
                type="text"
                className="domain-input"
                value={draft}
                disabled={disabled}
                data-testid="destination-fill-input"
                onChange={(event) => setDraft(event.target.value)}
              />
              <div className="domain-correction__actions">
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled || draft.trim() === ''}
                  data-testid="destination-fill-save"
                  onClick={() => {
                    const missing = entry.reading.missing[0]
                    if (missing === 'what the next step is') onMilestone(entry, draft)
                    else if (missing === 'where you are starting from') {
                      onRevise(entry, { baseline: draft })
                    } else if (missing === 'what would count as getting somewhere') {
                      onRevise(entry, { evidence: [draft.trim()] })
                    } else onRevise(entry, { unknowns: [draft.trim()] })
                    setFilling(undefined)
                    setDraft('')
                  }}
                >
                  Save
                </button>
                <button
                  type="button"
                  className="domain-correction__cancel"
                  disabled={disabled}
                  onClick={() => setFilling(undefined)}
                >
                  Leave it
                </button>
              </div>
            </div>
          ) : entry.reading.missing.length === 0 ? null : (
            <button
              type="button"
              className="domain-linkish"
              disabled={disabled}
              data-testid="destination-fill"
              onClick={() => {
                setFilling(entry.destination.source)
                setDraft('')
              }}
            >
              Fill that in
            </button>
          )}
        </div>
      ))}

      {!proving ? null : naming ? (
        <div className="domain-correction" data-testid="destination-form">
          <label className="domain-correction__prompt" htmlFor="destination-aim">
            What are you hoping {area} eventually looks like?
          </label>
          <p className="note">
            This is kept as what you are aiming at, in your words. It is never scored, never turned
            into a percentage, and you can change it whenever it changes.
          </p>
          <input
            id="destination-aim"
            type="text"
            className="domain-input"
            value={aim}
            disabled={disabled}
            data-testid="destination-aim-input"
            onChange={(event) => setAim(event.target.value)}
          />
          <label className="domain-correction__prompt" htmlFor="destination-milestone">
            And the next step towards it, if you know it
          </label>
          <p className="note">
            {/*
              What will happen, and only if it will — QA-84-005.

              This read `describeMilestone(milestone || 'that', …)`, so an owner
              who left the optional box empty — the ordinary case, and the one
              D-173 exists to protect — was told *"The next step in Career &
              Learning: 'that'. The app will treat this as what you are
              currently studying, and start suggesting work on it."* None of
              that happened, correctly: a blank milestone creates nothing. The
              confirmation was false precisely where the owner is least able to
              check it.
            */}
            {milestoneConfirmation(milestone, filedIn ?? here, label(filedIn ?? here))}
          </p>
          <input
            id="destination-milestone"
            type="text"
            className="domain-input"
            value={milestone}
            disabled={disabled}
            data-testid="destination-milestone-input"
            onChange={(event) => setMilestone(event.target.value)}
          />
          {readingLine === undefined ? null : (
            <div data-testid="destination-reading-offer">
              <p className="note">{readingLine}</p>
              {offer === undefined ? null : (
                <div className="domain-options">
                  <button
                    type="button"
                    className="domain-option"
                    aria-pressed={filedIn === undefined && (answeredScope || !offer.asking)}
                    disabled={disabled}
                    data-testid="destination-keep"
                    onClick={() => {
                      setFileIn(undefined)
                      setAnsweredScope(true)
                    }}
                  >
                    {offer.keep}
                  </button>
                  {offer.options.map((option) => (
                    <button
                      key={option.domain}
                      type="button"
                      className="domain-option"
                      aria-pressed={filedIn === option.domain}
                      disabled={disabled}
                      data-testid={
                        offer.options.length === 1
                          ? 'destination-refile'
                          : `destination-refile-${option.domain}`
                      }
                      onClick={() => {
                        setFileIn(option.domain)
                        setAnsweredScope(true)
                      }}
                    >
                      {option.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}
          {proposal === undefined ? null : (
            <UnknownSet
              fromWords={reading?.unknowns ?? []}
              fromObject={proposal.unknowns.filter(
                (line) => !(reading?.unknowns ?? []).includes(line),
              )}
              testId="destination-unknowns"
            />
          )}
          <div className="domain-correction__actions">
            <button
              type="button"
              className="domain-option"
              disabled={disabled || aim.trim() === ''}
              data-testid="destination-save"
              onClick={() => {
                onName(
                  {
                    aim,
                    domain: filedIn ?? here,
                    ...(milestone.trim() === '' ? {} : { milestone }),
                  },
                  reading,
                )
                setNaming(false)
                setAim('')
                setMilestone('')
                setFileIn(undefined)
              }}
            >
              That is it
            </button>
            <button
              type="button"
              className="domain-correction__cancel"
              disabled={disabled}
              onClick={() => setNaming(false)}
            >
              Not now
            </button>
          </div>
        </div>
      ) : (
        <button
          type="button"
          className="domain-linkish"
          disabled={disabled}
          data-testid="destination-open"
          onClick={() => setNaming(true)}
        >
          Say what you are aiming at
        </button>
      )}
    </Panel>
  )
}

/**
 * What the app read in the words, and the two gestures that move it — routing
 * 91 round 1.
 *
 * ## Both directions, because a route that only goes one way is not reversible
 *
 * The first version rendered this row **only** for a reading the owner had
 * accepted, and offered only the withdrawal. Declining therefore wrote nothing
 * *and left nothing*: QA-91-001 showed that §6.3's own contract — decline, then
 * redo and accept — could not be performed at all, because the offer existed
 * for the length of one card and was gone.
 *
 * So the row is symmetric. A destination whose words still name another area
 * carries the offer; a destination whose reading is settled carries the way
 * back. Neither is a question, neither is on Now, and neither spends the
 * discovery budget — this is the object's own page, which is where the owner
 * goes when he wants to look at the object.
 *
 * ## And the gesture says what it will do before it does it
 *
 * Where a next step has been named, moving the aim moves what kind of thing
 * that step is, and the sentence naming it is `describeMilestone`'s — the same
 * one the app used when it was created. A gesture with a consequence states the
 * consequence first (D-218's shape), so this opens a small block rather than
 * acting on one press.
 */
function ReadingRow({
  entry,
  situation,
  disabled,
  deciding,
  onDecide,
  onWithdrawReading,
  onAcceptReading,
}: {
  entry: DomainDestination
  situation: Situation
  disabled: boolean
  deciding: boolean
  onDecide: (open: boolean) => void
  onWithdrawReading: (destination: DomainDestination) => void
  onAcceptReading: (destination: DomainDestination, reading: AimReading, into: LifeDomainId) => void
}) {
  const area = (id: LifeDomainId) => situation.domains.labelFor(id)
  const settled = entry.interpretation
  const offered =
    settled !== undefined
      ? undefined
      : readAimIn(entry.destination.aim, entry.destination.domain, situation)
  const into = settled === undefined ? offered?.offer : settled.askedIn
  if (into === undefined) return null

  /*
   * What the gesture will actually do to the step he named — QA-91-005.
   *
   * This showed `describeMilestone(next, into)`, which is the sentence for
   * **creating** a next step in an area: it told him the app would treat
   * *"Clear the credit card"* as what he is currently studying, and then it did.
   * The consequence a gesture states has to be the consequence it has.
   */
  const next = entry.destination.milestones.find(
    (milestone) => !milestone.reached && !milestone.setAside,
  )?.goal.statement

  return (
    <div className="destination__reading" data-testid="destination-reading">
      <p className="note">
        {settled === undefined
          ? describeReading(offered!, area)
          : `Read as being about ${area(settled.named)}, from ${settled.words
              .map((word) => `“${word}”`)
              .join(', ')}. You agreed to that; the words above are yours and were not changed.`}
      </p>

      {!deciding ? (
        <button
          type="button"
          className="domain-linkish"
          disabled={disabled}
          data-testid={
            settled === undefined ? 'destination-reading-accept' : 'destination-reading-withdraw'
          }
          onClick={() => onDecide(true)}
        >
          {settled === undefined ? `File it in ${area(into)}` : `Put it back in ${area(into)}`}
        </button>
      ) : (
        <div className="domain-correction" data-testid="destination-reading-consequence">
          <p className="note">
            {next === undefined
              ? `The aim moves to ${area(into)}. Your words stay exactly as they are.`
              : `The aim moves to ${area(into)}. “${next}” was the next step towards it here, so it is set aside — it stays on the record, and the app stops suggesting it.`}
          </p>
          <div className="domain-correction__actions">
            <button
              type="button"
              className="domain-option"
              disabled={disabled}
              data-testid="destination-reading-confirm"
              onClick={() => {
                if (settled === undefined && offered !== undefined) {
                  onAcceptReading(entry, offered, into)
                } else {
                  onWithdrawReading(entry)
                }
                onDecide(false)
              }}
            >
              Yes, move it
            </button>
            <button
              type="button"
              className="domain-correction__cancel"
              disabled={disabled}
              data-testid="destination-reading-cancel"
              onClick={() => onDecide(false)}
            >
              Leave it
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

function promptFor(entry: DomainDestination): string {
  const missing = entry.reading.missing[0]
  if (missing === 'what the next step is') return 'What would be the next step?'
  if (missing === 'where you are starting from') return 'Where are you with this right now?'
  if (missing === 'what would count as getting somewhere') {
    return 'What would tell you this was actually happening?'
  }
  return 'What are you not sure about?'
}

function noteFor(entry: DomainDestination): string {
  const missing = entry.reading.missing[0]
  if (missing === 'what the next step is') {
    return 'This becomes a milestone with its own date, and the app will start suggesting work towards it.'
  }
  if (missing === 'where you are starting from') {
    return 'This is kept as your starting point, in your words. Nothing is measured against it.'
  }
  if (missing === 'what would count as getting somewhere') {
    return 'This is kept as what would count. The app will never decide you have got there.'
  }
  return 'This is kept as an open question, so the app stops treating it as settled.'
}

// ---------------------------------------------------------------------------
// What has actually happened — F05, F11, package 2
// ---------------------------------------------------------------------------

/**
 * The six rungs, the courses and the milestones, as three different things.
 *
 * Gate item 2 in the shape it is written: *a completed session, a completed
 * course and a milestone are three different things on screen, and no surface
 * claims capability from attendance*. Each rung prints the sentence
 * `domain/progress.ts` generates for its own count, and beside it the thing
 * that rung is **not** evidence of — which is the half a progress display
 * usually leaves out and the half the review is about.
 */
/**
 * Which named object each rung is evidence about — QA-90-002.
 *
 * ## The defect this exists to close
 *
 * Every rung was rendered with `kind="evidence"`, including the one whose
 * visible measure is **Sessions done**. So the page that section 54 requires to
 * show *"a completed session, a completed course and a milestone are three
 * different things"* rendered two markers, both reading **Evidence**, and the
 * `session` kind was declared in `ui.tsx` and used nowhere in the product.
 *
 * A shared vocabulary that resolves every member to one word is not a shared
 * vocabulary — it is a label. The marker has to name the thing.
 *
 * ## Why a table, and why exhaustive
 *
 * Two of the seven rungs *are* one of the three named objects: `completion` is
 * a session, and `milestone` is a milestone. The other five are evidence
 * **about** an object rather than the object itself — "got part way", "how they
 * went", "what has stuck" — and `evidence` is the honest word for them.
 *
 * `Record<ProgressEvidence, ObjectKindName>` rather than a switch with a
 * default, so an eighth rung is a **compile error** rather than a rung that
 * silently inherits the generic marker. That is exactly how this defect
 * happened: a default that was right for most rows and wrong for the two that
 * mattered, with nothing to notice it.
 */
const RUNG_KIND: Record<ProgressEvidence, ObjectKindName> = {
  attempt: 'evidence',
  'part-done': 'evidence',
  completion: 'session',
  quality: 'evidence',
  'retained-capability': 'evidence',
  transfer: 'evidence',
  milestone: 'milestone',
}

export function ProgressPanel({
  data,
  reflection,
  disabled,
  onReflect,
}: {
  data: DomainPageData
  reflection: CourseReflection | undefined
  disabled: boolean
  onReflect: (reflection: CourseReflection, answer: OutcomeAnswer) => void
}) {
  const { progress } = data
  if (progress.rungs.length === 0 && progress.courses.length === 0 && reflection === undefined) {
    return null
  }

  return (
    <Panel title="What has actually happened">
      {/*
        Seven rungs, and the third line is the one the review is about — F05.

        ## What the typesetting has to do here

        Each rung is three sentences: what it is, what the record shows, and
        what that is **not** evidence of. Set as three grey paragraphs of
        descending size they read as a heading, a fact and a disclaimer, and a
        disclaimer is the line a reader skips. It is the opposite: it is the
        half that keeps a completed session from being read as a capability.

        So the rung is bound together by a rule on its leading edge and the
        third line is set at the same size as the second, one step quieter. It
        is a **second half of the statement**, not fine print underneath one.

        ## And no rung outranks another

        `PROGRESS_EVIDENCE` is an ordinal array and `rankOf` indexes it, which
        is exactly why nothing here may draw that order: a ladder rendered as a
        ladder is a scale, and a scale about the owner is what section 22
        forbids. There is no numbering, no track, no filled and unfilled states
        and no colour that climbs. Seven rungs look like seven statements.
      */}
      {progress.rungs.map((rung) => (
        <div key={rung.kind} className="rung" data-testid={`progress-${rung.kind}`}>
          <ObjectKind kind={RUNG_KIND[rung.kind]} />
          <p className="rung__label">{rung.label}</p>
          <p className="rung__says">{rung.says}</p>
          <p className="rung__not">{rung.doesNotSay}</p>
        </div>
      ))}

      {/*
        A course is its own kind of thing — section 54, gate item 2.

        "A completed session, a completed course and a milestone are three
        different things on the page." All three are on this page and all three
        used to be set identically; the marker is what makes them three.
      */}
      {progress.courses.length === 0 ? null : (
        <div className="rung" data-testid="progress-courses">
          <ObjectKind kind="course" />
          <p className="rung__label">Courses finished</p>
          <p className="rung__says">
            {progress.courses.map((course) => course.about ?? 'a course').join(', ')}
          </p>
          <p className="rung__not">
            A course finishing is not a session finishing, and neither is getting there.
          </p>
        </div>
      )}

      {reflection === undefined ? null : (
        <div className="domain-correction" data-testid="course-reflection">
          <p className="domain-correction__prompt">{reflection.prompt}</p>
          <p className="note">{reflection.note}</p>
          <div className="domain-options">
            {reflection.answers.map((answer) => (
              <button
                key={answer.id}
                type="button"
                className="domain-option"
                disabled={disabled}
                data-testid={`course-reflection-${answer.id}`}
                onClick={() => onReflect(reflection, answer)}
              >
                {answer.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// Introducing something — F04, F19, F36, package 3
// ---------------------------------------------------------------------------

const KIND_WORD: Record<AuthorableKind, string> = {
  goal: 'A goal',
  routine: 'Something I do',
  person: 'A person',
  place: 'A place',
  skill: 'Something I am learning',
  obligation: 'A part of my week',
}

/**
 * One create-and-confirm control for all six things — F04.
 *
 * Closed until tapped, like every other control on this page: a page that opens
 * with a form is the static questionnaire dump section 59 excludes.
 *
 * The confirmation step is not decoration. The owner reads what the app
 * understood, what it will create and **what it is not going to assume**, and
 * only then agrees. That last list is what E13 recorded him needing — typing
 * into a box with no way to tell whether the answer had been taken as a current
 * fact, a standing constraint, an aspiration or an event.
 */
export function AuthoringPanel({
  situation,
  domain,
  disabled,
  onCreate,
}: {
  situation: Situation
  domain: LifeDomainId
  disabled: boolean
  onCreate: (draft: AuthoringDraft) => void
}) {
  const [kind, setKind] = useState<AuthorableKind | undefined>(undefined)
  const [name, setName] = useState('')
  const [detail, setDetail] = useState('')
  const [dayId, setDayId] = useState('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')
  const [minutes, setMinutes] = useState<number | undefined>(undefined)
  const [outdoors, setOutdoors] = useState<boolean | undefined>(undefined)

  const on = dayFromInput(dayId)
  const startsAt = minutesFromClock(from)
  const endsAt = minutesFromClock(to)
  const draft: AuthoringDraft | undefined =
    kind === undefined
      ? undefined
      : {
          kind,
          name,
          domain,
          ...(detail.trim() === '' ? {} : { detail }),
          ...(on === undefined ? {} : { dayId: on }),
          ...(startsAt === undefined ? {} : { startsAt }),
          ...(endsAt === undefined ? {} : { endsAt }),
          ...(kind === 'routine' && minutes !== undefined ? { minutes } : {}),
          ...(kind === 'routine' && outdoors !== undefined ? { requiresLeaving: outdoors } : {}),
        }
  const proposal = draft === undefined ? undefined : proposeAuthoring(draft, situation)

  return (
    <Panel title="Tell the app about something">
      {kind === undefined ? (
        <div className="domain-options" data-testid="authoring-kinds">
          {AUTHORABLE_KINDS.map((option) => (
            <button
              key={option}
              type="button"
              className="domain-option"
              disabled={disabled}
              data-testid={`authoring-kind-${option}`}
              onClick={() => setKind(option)}
            >
              {KIND_WORD[option]}
            </button>
          ))}
        </div>
      ) : (
        <div className="domain-correction" data-testid="authoring-form">
          <label className="domain-correction__prompt" htmlFor="authoring-name">
            What do you call it?
          </label>
          <p className="note">
            The app renders what you call it, exactly. Nothing here is rephrased.
          </p>
          <input
            id="authoring-name"
            type="text"
            className="domain-input"
            value={name}
            disabled={disabled}
            data-testid="authoring-name"
            onChange={(event) => setName(event.target.value)}
          />

          {kind === 'goal' ? (
            <>
              <label className="domain-correction__prompt" htmlFor="authoring-day">
                By when, if you have a date in mind
              </label>
              <p className="note">Leave it empty and the app will not invent one.</p>
              <input
                id="authoring-day"
                type="date"
                className="domain-input"
                value={dayId}
                disabled={disabled}
                data-testid="authoring-day"
                onChange={(event) => setDayId(event.target.value)}
              />
            </>
          ) : null}

          {kind === 'obligation' ? (
            <>
              <label className="domain-correction__prompt" htmlFor="authoring-from">
                What time does it start?
              </label>
              <p className="note">
                Exact times, not rough ones — the app works around the span you give it.
              </p>
              <input
                id="authoring-from"
                type="time"
                className="domain-input"
                value={from}
                disabled={disabled}
                data-testid="authoring-from"
                onChange={(event) => setFrom(event.target.value)}
              />
              <label className="domain-correction__prompt" htmlFor="authoring-to">
                And what time does it end?
              </label>
              <p className="note">It has to end after it starts.</p>
              <input
                id="authoring-to"
                type="time"
                className="domain-input"
                value={to}
                disabled={disabled}
                data-testid="authoring-to"
                onChange={(event) => setTo(event.target.value)}
              />
              <label className="domain-correction__prompt" htmlFor="authoring-obligation-day">
                Which day?
              </label>
              <p className="note">One day for now. A weekly shape is the Day shape control.</p>
              <input
                id="authoring-obligation-day"
                type="date"
                className="domain-input"
                value={dayId}
                disabled={disabled}
                data-testid="authoring-obligation-day"
                onChange={(event) => setDayId(event.target.value)}
              />
            </>
          ) : null}

          {/*
            The two things a movement routine has to say about itself —
            AUD-0045, and C21's other half.

            Both optional, like everything else on this form. A routine with no
            size is suggested without a duration rather than with an invented
            one, and a routine he has not said anything about is treated as one
            he can do at home — the safe direction, because that answer only
            ever removes a move.

            They are here rather than inferred from the name because inferring
            them is precisely what F36 forbids: "a swim" tells the app nothing
            about how long his swim is, and guessing would put a number he never
            gave into a sentence he reads.
          */}
          {kind === 'routine' ? (
            <>
              <label className="domain-correction__prompt" htmlFor="authoring-minutes">
                Roughly how long does it take?
              </label>
              <p className="note">
                Leave it empty and the app suggests it without a length rather than inventing one.
              </p>
              <div className="domain-options" data-testid="authoring-routine-size">
                {[15, 30, 45, 60, 90].map((option) => (
                  <button
                    key={option}
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    aria-pressed={minutes === option}
                    data-testid={`authoring-minutes-${option}`}
                    onClick={() => setMinutes(minutes === option ? undefined : option)}
                  >
                    {`${option} minutes`}
                  </button>
                ))}
              </div>
              <p className="domain-correction__prompt" id="authoring-outdoors">
                Do you have to go out for it?
              </p>
              <p className="note">
                If you do, the app leaves it out on an evening you have said you cannot leave.
              </p>
              <div
                className="domain-options"
                role="group"
                aria-labelledby="authoring-outdoors"
                data-testid="authoring-routine-outdoors"
              >
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled}
                  aria-pressed={outdoors === true}
                  data-testid="authoring-outdoors-yes"
                  onClick={() => setOutdoors(outdoors === true ? undefined : true)}
                >
                  Yes, I go out
                </button>
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled}
                  aria-pressed={outdoors === false}
                  data-testid="authoring-outdoors-no"
                  onClick={() => setOutdoors(outdoors === false ? undefined : false)}
                >
                  No, I can do it here
                </button>
              </div>
            </>
          ) : null}

          <label className="domain-correction__prompt" htmlFor="authoring-detail">
            Anything else worth saying about it
          </label>
          <p className="note">
            Stored as you wrote it and shown back to you. The app does not read meaning into it.
          </p>
          <input
            id="authoring-detail"
            type="text"
            className="domain-input"
            value={detail}
            disabled={disabled}
            data-testid="authoring-detail"
            onChange={(event) => setDetail(event.target.value)}
          />

          {proposal === undefined ? null : (
            <div data-testid="authoring-proposal">
              <p className="domain-correction__prompt">{proposal.interpretation}</p>
              {proposal.creates.length === 0 ? null : (
                <ul className="domain-destination__list">
                  {proposal.creates.map((line) => (
                    <li key={line}>{line}</li>
                  ))}
                </ul>
              )}
              {proposal.unknowns.length === 0 ? null : (
                <p className="note" data-testid="authoring-unknowns">
                  The app will not assume {proposal.unknowns.join(', ')}.
                </p>
              )}
              {proposal.problems.map((problem) => (
                <p key={problem} className="note" data-testid="authoring-problem">
                  {problem}
                </p>
              ))}
            </div>
          )}

          <div className="domain-correction__actions">
            <button
              type="button"
              className="domain-option"
              disabled={disabled || proposal === undefined || proposal.problems.length > 0}
              data-testid="authoring-save"
              onClick={() => {
                if (draft === undefined) return
                onCreate(draft)
                setKind(undefined)
                setName('')
                setDetail('')
                setDayId('')
                setFrom('')
                setTo('')
              }}
            >
              Yes, that is it
            </button>
            <button
              type="button"
              className="domain-correction__cancel"
              disabled={disabled}
              onClick={() => setKind(undefined)}
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </Panel>
  )
}

/**
 * Something that happened with somebody — F19.
 *
 * Only appears once a person exists in this area, which is the honest
 * precondition: the control names a person from the graph rather than asking
 * for one, so it cannot exist before {@link AuthoringPanel} has been used. That
 * is also why the two sit on the same page.
 */
export function PeoplePanel({
  people,
  disabled,
  onEvent,
}: {
  people: readonly { readonly ref: EntityRef; readonly label: string }[]
  disabled: boolean
  onEvent: (person: EntityRef, nature: string) => void
}) {
  const [open, setOpen] = useState<string | undefined>(undefined)
  const [draft, setDraft] = useState('')

  if (people.length === 0) return null

  return (
    <Panel title="People here">
      {people.map((person) => (
        <div key={person.ref.id} className="domain-skill" data-testid="domain-person">
          <p className="domain-skill__name">{person.label}</p>
          {open === person.ref.id ? (
            <div className="domain-correction">
              <label className="domain-correction__prompt" htmlFor={`person-${person.ref.id}`}>
                What happened with {person.label}?
              </label>
              <p className="note">
                Stored as you wrote it, against them. It is never graded, and no meaning is read
                into it.
              </p>
              <input
                id={`person-${person.ref.id}`}
                type="text"
                className="domain-input"
                value={draft}
                disabled={disabled}
                data-testid="person-event-input"
                onChange={(event) => setDraft(event.target.value)}
              />
              <div className="domain-correction__actions">
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled || draft.trim() === ''}
                  data-testid="person-event-save"
                  onClick={() => {
                    onEvent(person.ref, draft)
                    setOpen(undefined)
                    setDraft('')
                  }}
                >
                  Save
                </button>
                <button
                  type="button"
                  className="domain-correction__cancel"
                  disabled={disabled}
                  onClick={() => setOpen(undefined)}
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <button
              type="button"
              className="domain-linkish"
              disabled={disabled}
              aria-label={`Something happened with ${person.label}`}
              data-testid="person-event-open"
              onClick={() => {
                setOpen(person.ref.id)
                setDraft('')
              }}
            >
              Something happened
            </button>
          )}
        </div>
      ))}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// What was in the way — F07, package 5
// ---------------------------------------------------------------------------

export function BlockersPanel({
  blockers,
  disabled,
  onLift,
}: {
  blockers: readonly StandingBlocker[]
  disabled: boolean
  onLift: (blocker: StandingBlocker) => void
}) {
  if (blockers.length === 0) return null
  return (
    <Panel title="Things you said were in the way">
      <p className="note">
        These are about the world rather than about one evening, so the app keeps them until you say
        otherwise. Nothing here is read as you not wanting to.
      </p>
      {blockers.map((blocker) => (
        <div key={blocker.record} className="domain-veto" data-testid="domain-blocker">
          <p className="domain-veto__statement">{blocker.description}</p>
          <button
            type="button"
            className="domain-correction__cancel"
            disabled={disabled}
            aria-label={`Not true any more: ${blocker.description}`}
            data-testid="domain-blocker-lift"
            onClick={() => onLift(blocker)}
          >
            Not true any more
          </button>
        </div>
      ))}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// Correcting what was recorded — F32, D-165, package 6
// ---------------------------------------------------------------------------

/**
 * Withdrawing an entry, and moving one to the day it happened.
 *
 * Both say what they will do **before** they do it — D-165 — and both say what
 * they leave alone, which is the half that makes the gesture safe to press. The
 * third thing routing 83 found no route to, backfilling an entry that was never
 * recorded, is deliberately not here: D-165 leaves authoring a historical event
 * in the later Reach package with AUD-0050's retraction half.
 */
export function CorrectionsPanel({
  events,
  disabled,
  onWithdraw,
  onRedate,
}: {
  events: readonly CorrectableEvent[]
  disabled: boolean
  onWithdraw: (event: CorrectableEvent) => void
  onRedate: (event: CorrectableEvent, dayId: string) => void
}) {
  const [open, setOpen] = useState<string | undefined>(undefined)
  const [gesture, setGesture] = useState<CorrectionGesture>('event')
  const [day, setDay] = useState('')

  if (events.length === 0) return null

  return (
    <Panel title="Something here wrong?" tone="quiet">
      <p className="note">
        Nothing is deleted. An entry you withdraw stays in your history, marked as withdrawn.
      </p>
      {events.map((event) => {
        const consequence = correctionConsequence(gesture, `“${event.text}”`)
        return (
          <div key={event.id} className="domain-recent__row" data-testid="correctable-event">
            <span className="domain-recent__text">{event.text}</span>
            {open === event.id ? (
              <div className="domain-correction" data-testid="correction-open">
                {/*
                  A correction is one of the eight objects too — QA-90-002.

                  Marked once the gesture is open rather than on every row: the
                  closed row is the *event*, and what the marker names is the
                  thing the owner is about to do to it. Putting it on the row
                  would label his history as a correction, which it is not.
                */}
                <ObjectKind kind="correction" />
                <div className="domain-options">
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-gesture-event"
                    onClick={() => setGesture('event')}
                  >
                    This did not happen
                  </button>
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-gesture-timing"
                    onClick={() => setGesture('event-timing')}
                  >
                    It was a different day
                  </button>
                </div>

                <p className="domain-correction__prompt" data-testid="correction-consequence">
                  {consequence.consequence}
                </p>
                <p className="note" data-testid="correction-preserved">
                  {consequence.preserved} {consequence.reversal}
                </p>

                {gesture === 'event-timing' ? (
                  <>
                    <label className="domain-correction__prompt" htmlFor={`redate-${event.id}`}>
                      Which day did it actually happen?
                    </label>
                    <p className="note">
                      The entry moves to that day. When you wrote it down does not change.
                    </p>
                    <input
                      id={`redate-${event.id}`}
                      type="date"
                      className="domain-input"
                      value={day === '' ? event.dayId : day}
                      disabled={disabled}
                      data-testid="correction-day"
                      onChange={(event_) => setDay(event_.target.value)}
                    />
                  </>
                ) : null}

                <div className="domain-correction__actions">
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-apply"
                    onClick={() => {
                      if (gesture === 'event') onWithdraw(event)
                      else onRedate(event, day === '' ? event.dayId : day)
                      setOpen(undefined)
                      setDay('')
                    }}
                  >
                    Do it
                  </button>
                  <button
                    type="button"
                    className="domain-correction__cancel"
                    disabled={disabled}
                    onClick={() => setOpen(undefined)}
                  >
                    Leave it
                  </button>
                </div>
              </div>
            ) : (
              <button
                type="button"
                className="domain-linkish"
                disabled={disabled}
                aria-label={`Correct: ${event.text}`}
                data-testid="correction-open-button"
                onClick={() => {
                  setOpen(event.id)
                  setGesture('event')
                  setDay('')
                }}
              >
                Not right?
              </button>
            )}
          </div>
        )
      })}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// The private permission — D-167, package 6
// ---------------------------------------------------------------------------

/**
 * One control, off by default.
 *
 * The label and the note are read from `domain/privacy.ts`, beside the policy
 * that enforces them — D-175's rule. What this promises and what
 * `createFactReader` does are one sentence in one file, so they cannot drift
 * apart the way the Private page's old promise did.
 */
export function PermissionPanel({
  granted,
  disabled,
  onSet,
}: {
  granted: boolean
  disabled: boolean
  onSet: (granted: boolean) => void
}) {
  const definition = permissionDefinition('private-influence')
  return (
    /*
     * Its own classes, and the reason is coherence rather than tidiness.
     *
     * This borrowed `.domain-veto` from the standing-blockers panel and
     * `.domain-progress__says` from a rung of the progress ladder. A permission
     * is neither: a veto is something the owner ruled out, a rung is what the
     * record shows, and this is a standing decision he can take back. Three
     * meanings sharing two class names is how one of them eventually gets
     * restyled by a change aimed at another — the drift `.origin-badge` in
     * `base.css` is already the written record of.
     *
     * The copy is untouched and still comes from `domain/privacy.ts`, beside
     * the policy that enforces it (D-175).
     */
    <Panel title="What the app may reason from">
      <div className="permission" data-testid="permission">
        <ObjectKind kind="permission" />
        <p className="permission__label">{definition.label}</p>
        <p className="note">{definition.note}</p>
        <p className="permission__state" data-testid="permission-state">
          {granted ? definition.granted : definition.withheld}
        </p>
        <button
          type="button"
          className="domain-option"
          disabled={disabled}
          aria-label={granted ? 'Stop this influencing recommendations' : definition.label}
          data-testid="permission-toggle"
          onClick={() => onSet(!granted)}
        >
          {granted
            ? 'Stop it influencing recommendations'
            : 'Allow it to influence recommendations'}
        </button>
      </div>
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// What was in the way, asked once — F07, D-164
// ---------------------------------------------------------------------------

/**
 * The blocker question, and the silence where there is not one.
 *
 * Rendered from a {@link BlockerDecision}, which never returns "nothing": it
 * either asks or says why it is not asking. The silent branch renders a line
 * rather than nothing at all, because *"the app already knows what is in the
 * way"* is a useful thing for the owner to see and an empty space is not.
 */
export function BlockerQuestion({
  decision,
  disabled,
  onAnswer,
  onLeave,
}: {
  decision: BlockerDecision
  disabled: boolean
  onAnswer: (cause: string) => void
  onLeave: () => void
}) {
  if (!decision.ask) {
    return (
      <div className="now-blocker" data-testid="blocker-silent">
        <p className="note" data-testid="blocker-silent-detail">
          {decision.detail}
        </p>
      </div>
    )
  }

  return (
    <div className="now-blocker" data-testid="blocker-question">
      <p className="domain-correction__prompt">{decision.prompt}</p>
      <p className="note">{decision.note}</p>
      <div className="domain-options">
        {decision.options.map((option) => (
          <button
            key={option.id}
            type="button"
            className="domain-option"
            disabled={disabled}
            data-testid={`blocker-${option.id}`}
            onClick={() => onAnswer(option.id)}
          >
            {option.label}
          </button>
        ))}
        <button
          type="button"
          className="domain-correction__cancel"
          disabled={disabled}
          data-testid="blocker-leave"
          onClick={onLeave}
        >
          Just leave it
        </button>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// The two standing controls, in one place — AUD-0038(a)
// ---------------------------------------------------------------------------

/**
 * *"I've been keeping on top of this"* and *"Something's changed"*.
 *
 * ## The finding, which is about a loop rather than a control
 *
 * The coverage limiter on Now said *"Out of date — nothing has come in about
 * career & learning for four months"* and had nothing attached to it. The Life
 * domain page for the same area offered both of these. So the app raised the
 * flag on the screen the owner actually reads and put the response two taps
 * away, on a page section 8 exists to stop him having to patrol.
 *
 * ## Why one component rather than the same markup twice
 *
 * The audit's own test requirement is that Now's controls *"write the same
 * records as the Life page"*, and the cheapest way for that to stop being true
 * is two copies drifting — which is exactly how the premise and `freeTime` came
 * to disagree about a hundred and twenty minutes (AUD-0038(b), a finding in the
 * same entry). D-178: one name for a thing, in the layer every surface can
 * reach. The records are written by the caller, from `coverageInterpretationRecord`
 * and `domainStatusCorrectionRecord`, so there is one definition of what each
 * button means as well as one of how it looks.
 *
 * ## What it does not become
 *
 * Not a task, and not a nag. It draws only where the app is genuinely out of
 * date about an area, it is two links and one field, and saying *"I've been
 * keeping on top of this"* closes it without asking for anything else. D-075's
 * lesson — a screen that lists every true thing is homework — applies to Now
 * more sharply than to Life, because Now is read with one thumb.
 */
export function StandingControls({
  label,
  inputId,
  disabled,
  open,
  draft,
  onOpen,
  onClose,
  onDraftChange,
  onReviewed,
  onSubmit,
}: {
  label: string
  inputId: string
  disabled: boolean
  open: boolean
  draft: string
  onOpen: () => void
  onClose: () => void
  onDraftChange: (value: string) => void
  onReviewed: () => void
  onSubmit: (summary: string) => void
}) {
  if (!open) {
    return (
      <div className="domain-correction__actions" data-testid="standing-controls">
        <button
          type="button"
          className="domain-linkish"
          disabled={disabled}
          data-testid="standing-reviewed"
          onClick={onReviewed}
        >
          I've been keeping on top of this
        </button>
        <button
          type="button"
          className="domain-linkish"
          disabled={disabled}
          data-testid="standing-changed"
          onClick={onOpen}
        >
          Something's changed
        </button>
      </div>
    )
  }

  /*
   * A name, and a stated expectation — F40, D-176.
   *
   * The label is visible rather than an `aria-label`, and the note says where
   * the answer goes. A placeholder would satisfy neither: it is not read by
   * assistive technology reliably, and it disappears the moment there is
   * anything in the field — which is precisely when the owner most wants to
   * know what the app is about to do with what he typed.
   */
  return (
    <div className="domain-correction" data-testid="standing-controls">
      <label className="domain-correction__prompt" htmlFor={inputId}>
        What has changed in {label}?
      </label>
      <p className="domain-correction__note">
        In your own words. It joins this area’s history as something you told the app, and it is
        what brings the picture back up to date.
      </p>
      <input
        id={inputId}
        type="text"
        className="domain-input"
        value={draft}
        disabled={disabled}
        data-testid="standing-input"
        onChange={(event) => onDraftChange(event.target.value)}
      />
      <div className="domain-correction__actions">
        <button
          type="button"
          className="domain-option"
          disabled={disabled || draft.trim() === ''}
          data-testid="standing-save"
          onClick={() => onSubmit(draft)}
        >
          Save
        </button>
        <button
          type="button"
          className="domain-correction__cancel"
          disabled={disabled}
          data-testid="standing-cancel"
          onClick={onClose}
        >
          Cancel
        </button>
      </div>
    </div>
  )
}
