import { useState } from 'react'
import { Panel } from '../../components/ui'
import type { LifeDomainId } from '../../domain/domains'
import type { EntityRef } from '../../domain/entities'
import { permissionDefinition } from '../../domain/privacy'
import { correctionConsequence, type CorrectionGesture } from '../../intelligence/corrections'
import {
  AUTHORABLE_KINDS,
  dayFromInput,
  milestoneConfirmation,
  minutesFromClock,
  proposeAuthoring,
  PROVING_DOMAINS,
  type AuthorableKind,
  type AuthoringDraft,
  type DestinationDraft,
} from '../../intelligence/authoring'
import type { CourseReflection } from '../../intelligence/progress'
import type { OutcomeAnswer } from '../../intelligence/outcomes'
import type { BlockerDecision } from '../../intelligence/blockers'
import type { Situation } from '../../intelligence/situation'
import type {
  CorrectableEvent,
  DomainDestination,
  DomainPageData,
  StandingBlocker,
} from './domainPages'

/**
 * The panels routing 84 adds to a domain page.
 *
 * Presentational only, and deliberately so: **no function in this file builds a
 * record**. Every handler is passed down from `DomainPage.tsx`, which is where
 * the builders are called and therefore where the ordinary-use instrument's
 * route table finds them (`tests/synthetic/journey.ts`). Splitting the markup
 * out keeps one screen's worth of controls readable without moving a single
 * control off that screen.
 *
 * Two rules hold across everything below, and both are enforced elsewhere and
 * honoured here.
 *
 * **Every input has a name and says what the answer is for** — D-176. A
 * `<label>` that points at the control, and a note in view while he types
 * saying what the app will do with it. `architecture-guards.test.ts` fails the
 * build without the first; the second is the half a checker cannot see and the
 * half E13 recorded the owner needing.
 *
 * **Nothing here shows a number about him** — D-162. No percentage, no share,
 * no bar, no readiness figure, about the owner or about Adaya. A phase whose
 * whole subject is progress is where one arrives looking reasonable, so the
 * counts that do appear are counts of things that happened, generated by
 * `domain/progress.ts` from the evidence behind them.
 */

// ---------------------------------------------------------------------------
// What the owner is trying to become — F01, F35, package 1
// ---------------------------------------------------------------------------

/**
 * Where a destination may be named — the adjudication's proving scope.
 *
 * Career, Health and Money, and **not Fatherhood**: *"the growth model is the
 * product's best-evidenced mechanism, Phases 81 and 82 each corrected it, and
 * it is the hardest place to prove a new object and the worst place to break
 * one. It joins once the shape is proved."*
 *
 * The panel is absent on the other pages rather than empty. An empty one would
 * be the app inviting him to fill in something it is not ready to hold, and
 * every domain page in this product is a report before it is a form.
 */
export function DestinationPanel({
  data,
  area,
  disabled,
  onName,
  onRevise,
  onMilestone,
}: {
  data: DomainPageData
  area: string
  disabled: boolean
  onName: (draft: DestinationDraft) => void
  onRevise: (
    destination: DomainDestination,
    changes: { baseline?: string; evidence?: readonly string[]; unknowns?: readonly string[] },
  ) => void
  onMilestone: (destination: DomainDestination, statement: string) => void
}) {
  const [naming, setNaming] = useState(false)
  const [aim, setAim] = useState('')
  const [milestone, setMilestone] = useState('')
  const [filling, setFilling] = useState<string | undefined>(undefined)
  const [draft, setDraft] = useState('')

  /*
   * Three proving domains, not twelve.
   *
   * A destination already recorded is always shown — an area that gained one
   * before this rule, or through an import, must not have it silently hidden —
   * and the control that makes a new one is offered only where the object is
   * proved.
   */
  const proving = PROVING_DOMAINS.includes(data.page.domains[0]!)
  if (!proving && data.destinations.length === 0) return null

  return (
    <Panel title="What you are aiming at">
      {data.destinations.length === 0 ? (
        <p className="note" data-testid="destination-empty">
          Nothing here says what {area} is for. That is the one thing the app cannot work out on its
          own.
        </p>
      ) : null}

      {data.destinations.map((entry) => (
        <div key={entry.destination.source} className="domain-goal" data-testid="destination">
          <p className="domain-goal__statement" data-testid="destination-aim">
            {entry.reading.aim}
          </p>
          <dl className="domain-destination">
            <dt>Where you are</dt>
            <dd data-testid="destination-baseline">{entry.reading.baseline}</dd>
            <dt>Next</dt>
            <dd data-testid="destination-next">{entry.reading.next}</dd>
            {entry.reading.evidence.length === 0 ? null : (
              <>
                <dt>What would count</dt>
                <dd>
                  <ul className="domain-destination__list">
                    {entry.reading.evidence.map((line) => (
                      <li key={line}>{line}</li>
                    ))}
                  </ul>
                </dd>
              </>
            )}
            {entry.reading.unknowns.length === 0 ? null : (
              <>
                <dt>Not sure about</dt>
                <dd>
                  <ul className="domain-destination__list">
                    {entry.reading.unknowns.map((line) => (
                      <li key={line}>{line}</li>
                    ))}
                  </ul>
                </dd>
              </>
            )}
          </dl>

          {entry.destination.milestones.length === 0 ? null : (
            <ul className="domain-goal__parts" data-testid="destination-milestones">
              {entry.destination.milestones.map((milestone) => (
                <li key={milestone.goal.source} className="domain-goal__part">
                  <span className="domain-goal__part-name">{milestone.goal.statement}</span>
                  {/*
                    Three words, and they are three different facts — gate item 2.

                    "Reached" is the owner having said so on this milestone.
                    It is not a session having happened and it is not a course
                    having finished; both of those are counted separately, under
                    their own names, in the panel below.
                  */}
                  <span className="domain-goal__part-state">
                    {milestone.reached ? 'reached' : 'still ahead'}
                  </span>
                </li>
              ))}
            </ul>
          )}

          {entry.reading.missing.length === 0 ? null : (
            <p className="note" data-testid="destination-missing">
              The app does not know {entry.reading.missing.join(', ')}.
            </p>
          )}

          {filling === entry.destination.source ? (
            <div className="domain-correction">
              <label
                className="domain-correction__prompt"
                htmlFor={`destination-fill-${entry.destination.source}`}
              >
                {promptFor(entry)}
              </label>
              <p className="note">{noteFor(entry)}</p>
              <input
                id={`destination-fill-${entry.destination.source}`}
                type="text"
                className="domain-input"
                value={draft}
                disabled={disabled}
                data-testid="destination-fill-input"
                onChange={(event) => setDraft(event.target.value)}
              />
              <div className="domain-correction__actions">
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled || draft.trim() === ''}
                  data-testid="destination-fill-save"
                  onClick={() => {
                    const missing = entry.reading.missing[0]
                    if (missing === 'what the next step is') onMilestone(entry, draft)
                    else if (missing === 'where you are starting from') {
                      onRevise(entry, { baseline: draft })
                    } else if (missing === 'what would count as getting somewhere') {
                      onRevise(entry, { evidence: [draft.trim()] })
                    } else onRevise(entry, { unknowns: [draft.trim()] })
                    setFilling(undefined)
                    setDraft('')
                  }}
                >
                  Save
                </button>
                <button
                  type="button"
                  className="domain-correction__cancel"
                  disabled={disabled}
                  onClick={() => setFilling(undefined)}
                >
                  Leave it
                </button>
              </div>
            </div>
          ) : entry.reading.missing.length === 0 ? null : (
            <button
              type="button"
              className="domain-linkish"
              disabled={disabled}
              data-testid="destination-fill"
              onClick={() => {
                setFilling(entry.destination.source)
                setDraft('')
              }}
            >
              Fill that in
            </button>
          )}
        </div>
      ))}

      {!proving ? null : naming ? (
        <div className="domain-correction" data-testid="destination-form">
          <label className="domain-correction__prompt" htmlFor="destination-aim">
            What are you hoping {area} eventually looks like?
          </label>
          <p className="note">
            This is kept as what you are aiming at, in your words. It is never scored, never turned
            into a percentage, and you can change it whenever it changes.
          </p>
          <input
            id="destination-aim"
            type="text"
            className="domain-input"
            value={aim}
            disabled={disabled}
            data-testid="destination-aim-input"
            onChange={(event) => setAim(event.target.value)}
          />
          <label className="domain-correction__prompt" htmlFor="destination-milestone">
            And the next step towards it, if you know it
          </label>
          <p className="note">
            {/*
              What will happen, and only if it will — QA-84-005.

              This read `describeMilestone(milestone || 'that', …)`, so an owner
              who left the optional box empty — the ordinary case, and the one
              D-173 exists to protect — was told *"The next step in Career &
              Learning: 'that'. The app will treat this as what you are
              currently studying, and start suggesting work on it."* None of
              that happened, correctly: a blank milestone creates nothing. The
              confirmation was false precisely where the owner is least able to
              check it.
            */}
            {milestoneConfirmation(milestone, data.page.domains[0]!, area)}
          </p>
          <input
            id="destination-milestone"
            type="text"
            className="domain-input"
            value={milestone}
            disabled={disabled}
            data-testid="destination-milestone-input"
            onChange={(event) => setMilestone(event.target.value)}
          />
          <div className="domain-correction__actions">
            <button
              type="button"
              className="domain-option"
              disabled={disabled || aim.trim() === ''}
              data-testid="destination-save"
              onClick={() => {
                onName({
                  aim,
                  domain: data.page.domains[0]!,
                  ...(milestone.trim() === '' ? {} : { milestone }),
                })
                setNaming(false)
                setAim('')
                setMilestone('')
              }}
            >
              That is it
            </button>
            <button
              type="button"
              className="domain-correction__cancel"
              disabled={disabled}
              onClick={() => setNaming(false)}
            >
              Not now
            </button>
          </div>
        </div>
      ) : (
        <button
          type="button"
          className="domain-linkish"
          disabled={disabled}
          data-testid="destination-open"
          onClick={() => setNaming(true)}
        >
          Say what you are aiming at
        </button>
      )}
    </Panel>
  )
}

function promptFor(entry: DomainDestination): string {
  const missing = entry.reading.missing[0]
  if (missing === 'what the next step is') return 'What would be the next step?'
  if (missing === 'where you are starting from') return 'Where are you with this right now?'
  if (missing === 'what would count as getting somewhere') {
    return 'What would tell you this was actually happening?'
  }
  return 'What are you not sure about?'
}

function noteFor(entry: DomainDestination): string {
  const missing = entry.reading.missing[0]
  if (missing === 'what the next step is') {
    return 'This becomes a milestone with its own date, and the app will start suggesting work towards it.'
  }
  if (missing === 'where you are starting from') {
    return 'This is kept as your starting point, in your words. Nothing is measured against it.'
  }
  if (missing === 'what would count as getting somewhere') {
    return 'This is kept as what would count. The app will never decide you have got there.'
  }
  return 'This is kept as an open question, so the app stops treating it as settled.'
}

// ---------------------------------------------------------------------------
// What has actually happened — F05, F11, package 2
// ---------------------------------------------------------------------------

/**
 * The six rungs, the courses and the milestones, as three different things.
 *
 * Gate item 2 in the shape it is written: *a completed session, a completed
 * course and a milestone are three different things on screen, and no surface
 * claims capability from attendance*. Each rung prints the sentence
 * `domain/progress.ts` generates for its own count, and beside it the thing
 * that rung is **not** evidence of — which is the half a progress display
 * usually leaves out and the half the review is about.
 */
export function ProgressPanel({
  data,
  reflection,
  disabled,
  onReflect,
}: {
  data: DomainPageData
  reflection: CourseReflection | undefined
  disabled: boolean
  onReflect: (reflection: CourseReflection, answer: OutcomeAnswer) => void
}) {
  const { progress } = data
  if (progress.rungs.length === 0 && progress.courses.length === 0 && reflection === undefined) {
    return null
  }

  return (
    <Panel title="What has actually happened">
      {progress.rungs.map((rung) => (
        <div key={rung.kind} className="domain-progress" data-testid={`progress-${rung.kind}`}>
          <p className="domain-progress__label">{rung.label}</p>
          <p className="domain-progress__says">{rung.says}</p>
          <p className="note">{rung.doesNotSay}</p>
        </div>
      ))}

      {progress.courses.length === 0 ? null : (
        <div className="domain-progress" data-testid="progress-courses">
          <p className="domain-progress__label">Courses finished</p>
          <p className="domain-progress__says">
            {progress.courses.map((course) => course.about ?? 'a course').join(', ')}
          </p>
          <p className="note">
            A course finishing is not a session finishing, and neither is getting there.
          </p>
        </div>
      )}

      {reflection === undefined ? null : (
        <div className="domain-correction" data-testid="course-reflection">
          <p className="domain-correction__prompt">{reflection.prompt}</p>
          <p className="note">{reflection.note}</p>
          <div className="domain-options">
            {reflection.answers.map((answer) => (
              <button
                key={answer.id}
                type="button"
                className="domain-option"
                disabled={disabled}
                data-testid={`course-reflection-${answer.id}`}
                onClick={() => onReflect(reflection, answer)}
              >
                {answer.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// Introducing something — F04, F19, F36, package 3
// ---------------------------------------------------------------------------

const KIND_WORD: Record<AuthorableKind, string> = {
  goal: 'A goal',
  routine: 'Something I do',
  person: 'A person',
  place: 'A place',
  skill: 'Something I am learning',
  obligation: 'A part of my week',
}

/**
 * One create-and-confirm control for all six things — F04.
 *
 * Closed until tapped, like every other control on this page: a page that opens
 * with a form is the static questionnaire dump section 59 excludes.
 *
 * The confirmation step is not decoration. The owner reads what the app
 * understood, what it will create and **what it is not going to assume**, and
 * only then agrees. That last list is what E13 recorded him needing — typing
 * into a box with no way to tell whether the answer had been taken as a current
 * fact, a standing constraint, an aspiration or an event.
 */
export function AuthoringPanel({
  situation,
  domain,
  disabled,
  onCreate,
}: {
  situation: Situation
  domain: LifeDomainId
  disabled: boolean
  onCreate: (draft: AuthoringDraft) => void
}) {
  const [kind, setKind] = useState<AuthorableKind | undefined>(undefined)
  const [name, setName] = useState('')
  const [detail, setDetail] = useState('')
  const [dayId, setDayId] = useState('')
  const [from, setFrom] = useState('')
  const [to, setTo] = useState('')

  const on = dayFromInput(dayId)
  const startsAt = minutesFromClock(from)
  const endsAt = minutesFromClock(to)
  const draft: AuthoringDraft | undefined =
    kind === undefined
      ? undefined
      : {
          kind,
          name,
          domain,
          ...(detail.trim() === '' ? {} : { detail }),
          ...(on === undefined ? {} : { dayId: on }),
          ...(startsAt === undefined ? {} : { startsAt }),
          ...(endsAt === undefined ? {} : { endsAt }),
        }
  const proposal = draft === undefined ? undefined : proposeAuthoring(draft, situation)

  return (
    <Panel title="Tell the app about something">
      {kind === undefined ? (
        <div className="domain-options" data-testid="authoring-kinds">
          {AUTHORABLE_KINDS.map((option) => (
            <button
              key={option}
              type="button"
              className="domain-option"
              disabled={disabled}
              data-testid={`authoring-kind-${option}`}
              onClick={() => setKind(option)}
            >
              {KIND_WORD[option]}
            </button>
          ))}
        </div>
      ) : (
        <div className="domain-correction" data-testid="authoring-form">
          <label className="domain-correction__prompt" htmlFor="authoring-name">
            What do you call it?
          </label>
          <p className="note">
            The app renders what you call it, exactly. Nothing here is rephrased.
          </p>
          <input
            id="authoring-name"
            type="text"
            className="domain-input"
            value={name}
            disabled={disabled}
            data-testid="authoring-name"
            onChange={(event) => setName(event.target.value)}
          />

          {kind === 'goal' ? (
            <>
              <label className="domain-correction__prompt" htmlFor="authoring-day">
                By when, if you have a date in mind
              </label>
              <p className="note">Leave it empty and the app will not invent one.</p>
              <input
                id="authoring-day"
                type="date"
                className="domain-input"
                value={dayId}
                disabled={disabled}
                data-testid="authoring-day"
                onChange={(event) => setDayId(event.target.value)}
              />
            </>
          ) : null}

          {kind === 'obligation' ? (
            <>
              <label className="domain-correction__prompt" htmlFor="authoring-from">
                What time does it start?
              </label>
              <p className="note">
                Exact times, not rough ones — the app works around the span you give it.
              </p>
              <input
                id="authoring-from"
                type="time"
                className="domain-input"
                value={from}
                disabled={disabled}
                data-testid="authoring-from"
                onChange={(event) => setFrom(event.target.value)}
              />
              <label className="domain-correction__prompt" htmlFor="authoring-to">
                And what time does it end?
              </label>
              <p className="note">It has to end after it starts.</p>
              <input
                id="authoring-to"
                type="time"
                className="domain-input"
                value={to}
                disabled={disabled}
                data-testid="authoring-to"
                onChange={(event) => setTo(event.target.value)}
              />
              <label className="domain-correction__prompt" htmlFor="authoring-obligation-day">
                Which day?
              </label>
              <p className="note">One day for now. A weekly shape is the Day shape control.</p>
              <input
                id="authoring-obligation-day"
                type="date"
                className="domain-input"
                value={dayId}
                disabled={disabled}
                data-testid="authoring-obligation-day"
                onChange={(event) => setDayId(event.target.value)}
              />
            </>
          ) : null}

          <label className="domain-correction__prompt" htmlFor="authoring-detail">
            Anything else worth saying about it
          </label>
          <p className="note">
            Stored as you wrote it and shown back to you. The app does not read meaning into it.
          </p>
          <input
            id="authoring-detail"
            type="text"
            className="domain-input"
            value={detail}
            disabled={disabled}
            data-testid="authoring-detail"
            onChange={(event) => setDetail(event.target.value)}
          />

          {proposal === undefined ? null : (
            <div data-testid="authoring-proposal">
              <p className="domain-correction__prompt">{proposal.interpretation}</p>
              {proposal.creates.length === 0 ? null : (
                <ul className="domain-destination__list">
                  {proposal.creates.map((line) => (
                    <li key={line}>{line}</li>
                  ))}
                </ul>
              )}
              {proposal.unknowns.length === 0 ? null : (
                <p className="note" data-testid="authoring-unknowns">
                  The app will not assume {proposal.unknowns.join(', ')}.
                </p>
              )}
              {proposal.problems.map((problem) => (
                <p key={problem} className="note" data-testid="authoring-problem">
                  {problem}
                </p>
              ))}
            </div>
          )}

          <div className="domain-correction__actions">
            <button
              type="button"
              className="domain-option"
              disabled={disabled || proposal === undefined || proposal.problems.length > 0}
              data-testid="authoring-save"
              onClick={() => {
                if (draft === undefined) return
                onCreate(draft)
                setKind(undefined)
                setName('')
                setDetail('')
                setDayId('')
                setFrom('')
                setTo('')
              }}
            >
              Yes, that is it
            </button>
            <button
              type="button"
              className="domain-correction__cancel"
              disabled={disabled}
              onClick={() => setKind(undefined)}
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </Panel>
  )
}

/**
 * Something that happened with somebody — F19.
 *
 * Only appears once a person exists in this area, which is the honest
 * precondition: the control names a person from the graph rather than asking
 * for one, so it cannot exist before {@link AuthoringPanel} has been used. That
 * is also why the two sit on the same page.
 */
export function PeoplePanel({
  people,
  disabled,
  onEvent,
}: {
  people: readonly { readonly ref: EntityRef; readonly label: string }[]
  disabled: boolean
  onEvent: (person: EntityRef, nature: string) => void
}) {
  const [open, setOpen] = useState<string | undefined>(undefined)
  const [draft, setDraft] = useState('')

  if (people.length === 0) return null

  return (
    <Panel title="People here">
      {people.map((person) => (
        <div key={person.ref.id} className="domain-skill" data-testid="domain-person">
          <p className="domain-skill__name">{person.label}</p>
          {open === person.ref.id ? (
            <div className="domain-correction">
              <label className="domain-correction__prompt" htmlFor={`person-${person.ref.id}`}>
                What happened with {person.label}?
              </label>
              <p className="note">
                Stored as you wrote it, against them. It is never graded, and no meaning is read
                into it.
              </p>
              <input
                id={`person-${person.ref.id}`}
                type="text"
                className="domain-input"
                value={draft}
                disabled={disabled}
                data-testid="person-event-input"
                onChange={(event) => setDraft(event.target.value)}
              />
              <div className="domain-correction__actions">
                <button
                  type="button"
                  className="domain-option"
                  disabled={disabled || draft.trim() === ''}
                  data-testid="person-event-save"
                  onClick={() => {
                    onEvent(person.ref, draft)
                    setOpen(undefined)
                    setDraft('')
                  }}
                >
                  Save
                </button>
                <button
                  type="button"
                  className="domain-correction__cancel"
                  disabled={disabled}
                  onClick={() => setOpen(undefined)}
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <button
              type="button"
              className="domain-linkish"
              disabled={disabled}
              aria-label={`Something happened with ${person.label}`}
              data-testid="person-event-open"
              onClick={() => {
                setOpen(person.ref.id)
                setDraft('')
              }}
            >
              Something happened
            </button>
          )}
        </div>
      ))}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// What was in the way — F07, package 5
// ---------------------------------------------------------------------------

export function BlockersPanel({
  blockers,
  disabled,
  onLift,
}: {
  blockers: readonly StandingBlocker[]
  disabled: boolean
  onLift: (blocker: StandingBlocker) => void
}) {
  if (blockers.length === 0) return null
  return (
    <Panel title="Things you said were in the way">
      <p className="note">
        These are about the world rather than about one evening, so the app keeps them until you say
        otherwise. Nothing here is read as you not wanting to.
      </p>
      {blockers.map((blocker) => (
        <div key={blocker.record} className="domain-veto" data-testid="domain-blocker">
          <p className="domain-veto__statement">{blocker.description}</p>
          <button
            type="button"
            className="domain-correction__cancel"
            disabled={disabled}
            aria-label={`Not true any more: ${blocker.description}`}
            data-testid="domain-blocker-lift"
            onClick={() => onLift(blocker)}
          >
            Not true any more
          </button>
        </div>
      ))}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// Correcting what was recorded — F32, D-165, package 6
// ---------------------------------------------------------------------------

/**
 * Withdrawing an entry, and moving one to the day it happened.
 *
 * Both say what they will do **before** they do it — D-165 — and both say what
 * they leave alone, which is the half that makes the gesture safe to press. The
 * third thing routing 83 found no route to, backfilling an entry that was never
 * recorded, is deliberately not here: D-165 leaves authoring a historical event
 * in the later Reach package with AUD-0050's retraction half.
 */
export function CorrectionsPanel({
  events,
  disabled,
  onWithdraw,
  onRedate,
}: {
  events: readonly CorrectableEvent[]
  disabled: boolean
  onWithdraw: (event: CorrectableEvent) => void
  onRedate: (event: CorrectableEvent, dayId: string) => void
}) {
  const [open, setOpen] = useState<string | undefined>(undefined)
  const [gesture, setGesture] = useState<CorrectionGesture>('event')
  const [day, setDay] = useState('')

  if (events.length === 0) return null

  return (
    <Panel title="Something here wrong?">
      <p className="note">
        Nothing is deleted. An entry you withdraw stays in your history, marked as withdrawn.
      </p>
      {events.map((event) => {
        const consequence = correctionConsequence(gesture, `“${event.text}”`)
        return (
          <div key={event.id} className="domain-recent__row" data-testid="correctable-event">
            <span className="domain-recent__text">{event.text}</span>
            {open === event.id ? (
              <div className="domain-correction" data-testid="correction-open">
                <div className="domain-options">
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-gesture-event"
                    onClick={() => setGesture('event')}
                  >
                    This did not happen
                  </button>
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-gesture-timing"
                    onClick={() => setGesture('event-timing')}
                  >
                    It was a different day
                  </button>
                </div>

                <p className="domain-correction__prompt" data-testid="correction-consequence">
                  {consequence.consequence}
                </p>
                <p className="note" data-testid="correction-preserved">
                  {consequence.preserved} {consequence.reversal}
                </p>

                {gesture === 'event-timing' ? (
                  <>
                    <label className="domain-correction__prompt" htmlFor={`redate-${event.id}`}>
                      Which day did it actually happen?
                    </label>
                    <p className="note">
                      The entry moves to that day. When you wrote it down does not change.
                    </p>
                    <input
                      id={`redate-${event.id}`}
                      type="date"
                      className="domain-input"
                      value={day === '' ? event.dayId : day}
                      disabled={disabled}
                      data-testid="correction-day"
                      onChange={(event_) => setDay(event_.target.value)}
                    />
                  </>
                ) : null}

                <div className="domain-correction__actions">
                  <button
                    type="button"
                    className="domain-option"
                    disabled={disabled}
                    data-testid="correction-apply"
                    onClick={() => {
                      if (gesture === 'event') onWithdraw(event)
                      else onRedate(event, day === '' ? event.dayId : day)
                      setOpen(undefined)
                      setDay('')
                    }}
                  >
                    Do it
                  </button>
                  <button
                    type="button"
                    className="domain-correction__cancel"
                    disabled={disabled}
                    onClick={() => setOpen(undefined)}
                  >
                    Leave it
                  </button>
                </div>
              </div>
            ) : (
              <button
                type="button"
                className="domain-linkish"
                disabled={disabled}
                aria-label={`Correct: ${event.text}`}
                data-testid="correction-open-button"
                onClick={() => {
                  setOpen(event.id)
                  setGesture('event')
                  setDay('')
                }}
              >
                Not right?
              </button>
            )}
          </div>
        )
      })}
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// The private permission — D-167, package 6
// ---------------------------------------------------------------------------

/**
 * One control, off by default.
 *
 * The label and the note are read from `domain/privacy.ts`, beside the policy
 * that enforces them — D-175's rule. What this promises and what
 * `createFactReader` does are one sentence in one file, so they cannot drift
 * apart the way the Private page's old promise did.
 */
export function PermissionPanel({
  granted,
  disabled,
  onSet,
}: {
  granted: boolean
  disabled: boolean
  onSet: (granted: boolean) => void
}) {
  const definition = permissionDefinition('private-influence')
  return (
    <Panel title="What the app may reason from">
      <div className="domain-veto" data-testid="permission">
        <p className="domain-veto__statement">{definition.label}</p>
        <p className="note">{definition.note}</p>
        <p className="domain-progress__says" data-testid="permission-state">
          {granted ? definition.granted : definition.withheld}
        </p>
        <button
          type="button"
          className="domain-option"
          disabled={disabled}
          aria-label={granted ? 'Stop this influencing recommendations' : definition.label}
          data-testid="permission-toggle"
          onClick={() => onSet(!granted)}
        >
          {granted
            ? 'Stop it influencing recommendations'
            : 'Allow it to influence recommendations'}
        </button>
      </div>
    </Panel>
  )
}

// ---------------------------------------------------------------------------
// What was in the way, asked once — F07, D-164
// ---------------------------------------------------------------------------

/**
 * The blocker question, and the silence where there is not one.
 *
 * Rendered from a {@link BlockerDecision}, which never returns "nothing": it
 * either asks or says why it is not asking. The silent branch renders a line
 * rather than nothing at all, because *"the app already knows what is in the
 * way"* is a useful thing for the owner to see and an empty space is not.
 */
export function BlockerQuestion({
  decision,
  disabled,
  onAnswer,
  onLeave,
}: {
  decision: BlockerDecision
  disabled: boolean
  onAnswer: (cause: string) => void
  onLeave: () => void
}) {
  if (!decision.ask) {
    return (
      <div className="now-blocker" data-testid="blocker-silent">
        <p className="note" data-testid="blocker-silent-detail">
          {decision.detail}
        </p>
      </div>
    )
  }

  return (
    <div className="now-blocker" data-testid="blocker-question">
      <p className="domain-correction__prompt">{decision.prompt}</p>
      <p className="note">{decision.note}</p>
      <div className="domain-options">
        {decision.options.map((option) => (
          <button
            key={option.id}
            type="button"
            className="domain-option"
            disabled={disabled}
            data-testid={`blocker-${option.id}`}
            onClick={() => onAnswer(option.id)}
          >
            {option.label}
          </button>
        ))}
        <button
          type="button"
          className="domain-correction__cancel"
          disabled={disabled}
          data-testid="blocker-leave"
          onClick={onLeave}
        >
          Just leave it
        </button>
      </div>
    </div>
  )
}
